In [288]:
import pandas as pd
import zipfile

# Ruta local al archivo zip (ajústala si es diferente)
zip_path = 'C:/Users/evivas/Downloads/Datos_icfes_analitica.zip'

# Abrir el zip y leer el CSV dentro (ajusta el nombre del archivo si cambia)
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    with zip_ref.open('Datos_icfes.csv') as file:
        df = pd.read_csv(file)

df.head()

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global,partition_0
0,20172,CC,SB11201720219629,URBANO,NaN,A,ACADÉMICO,113433000021,113433000021,13,...,No,Si,A-,45.0,39.0,50,48,49,232,saber11-2017
1,20172,TI,SB11201720548913,RURAL,NaN,A,ACADÉMICO,241396000536,241396000536,41,...,No,Si,A-,36.0,50.0,45,48,49,235,saber11-2017
2,20172,TI,SB11201720208875,URBANO,N,A,TÉCNICO,176403000079,176403000079,76,...,Si,Si,A1,48.0,53.0,54,52,59,270,saber11-2017
3,20172,TI,SB11201720311306,URBANO,N,A,TÉCNICO,113468001038,113468001038,13,...,No,Si,A-,45.0,52.0,56,51,58,268,saber11-2017
4,20172,TI,SB11201720424646,RURAL,N,A,TÉCNICO/ACADÉMICO,273268001120,273268001120,73,...,Si,Si,A-,37.0,46.0,48,51,46,235,saber11-2017

In [289]:
#Conocer el nombre de las columnas 
df.columns
print(list(df.columns))

['periodo', 'estu_tipodocumento', 'estu_consecutivo', 'cole_area_ubicacion', 'cole_bilingue', 'cole_calendario', 'cole_caracter', 'cole_cod_dane_establecimiento', 'cole_cod_dane_sede', 'cole_cod_depto_ubicacion', 'cole_cod_mcpio_ubicacion', 'cole_codigo_icfes', 'cole_depto_ubicacion', 'cole_genero', 'cole_jornada', 'cole_mcpio_ubicacion', 'cole_naturaleza', 'cole_nombre_establecimiento', 'cole_nombre_sede', 'cole_sede_principal', 'estu_cod_depto_presentacion', 'estu_cod_mcpio_presentacion', 'estu_cod_reside_depto', 'estu_cod_reside_mcpio', 'estu_depto_presentacion', 'estu_depto_reside', 'estu_estadoinvestigacion', 'estu_estudiante', 'estu_fechanacimiento', 'estu_genero', 'estu_mcpio_presentacion', 'estu_mcpio_reside', 'estu_nacionalidad', 'estu_pais_reside', 'estu_privado_libertad', 'fami_cuartoshogar', 'fami_educacionmadre', 'fami_educacionpadre', 'fami_estratovivienda', 'fami_personashogar', 'fami_tieneautomovil', 'fami_tienecomputador', 'fami_tieneinternet', 'fami_tienelavadora', 'desemp_ingles', 'punt_ingles', 'punt_matematicas', 'punt_sociales_ciudadanas', 'punt_c_naturales', 'punt_lectura_critica', 'punt_global', 'partition_0']

In [290]:
#Eliminar columnas innecesarias, teniendo en cuenta las preguntas de negocio
df = df.drop(['estu_consecutivo', 'cole_area_ubicacion', 'cole_cod_dane_establecimiento','cole_cod_dane_sede','cole_cod_depto_ubicacion', 'cole_cod_mcpio_ubicacion','cole_codigo_icfes','cole_nombre_establecimiento', 'cole_nombre_sede', 'cole_sede_principal','estu_cod_depto_presentacion', 'estu_cod_mcpio_presentacion', 'estu_cod_reside_depto','estu_cod_reside_mcpio', 'estu_depto_presentacion', 'estu_depto_reside','estu_fechanacimiento','estu_mcpio_presentacion', 'estu_mcpio_reside','partition_0','cole_mcpio_ubicacion','estu_estadoinvestigacion','estu_estudiante'], axis=1)

In [291]:
# Contar la cantidad de datos faltantes en cada columna 
datos_faltantes = df.isna().sum()

# Mostrar el resultado
print(datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue               79551
cole_calendario                 0
cole_caracter                8685
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     6
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8823
fami_educacionmadre         24805
fami_educacionpadre         24806
fami_estratovivienda        27728
fami_personashogar          11614
fami_tieneautomovil         10530
fami_tienecomputador         9202
fami_tieneinternet          25707
fami_tienelavadora           8627
desemp_ingles                   7
punt_ingles                   123
punt_matematicas               11
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
dtype: int64

In [292]:
import pandas as pd

# Valores unicos de cada columna 
for column in df.columns:
    print(f"Valores únicos en la columna '{column}':")
    print(df[column].unique())
    print('-' * 40)

Valores únicos en la columna 'periodo':
[20172 20171]
----------------------------------------
Valores únicos en la columna 'estu_tipodocumento':
['CC' 'TI' 'CR' 'CE' 'V' 'RC' 'PE' 'PC' 'NUI' 'NUIP']
----------------------------------------
Valores únicos en la columna 'cole_bilingue':
[nan 'N' 'S']
----------------------------------------
Valores únicos en la columna 'cole_calendario':
['A' 'B' 'OTRO']
----------------------------------------
Valores únicos en la columna 'cole_caracter':
['ACADÉMICO' 'TÉCNICO' 'TÉCNICO/ACADÉMICO' nan 'NO APLICA']
----------------------------------------
Valores únicos en la columna 'cole_depto_ubicacion':
['BOLIVAR' 'HUILA' 'VALLE' 'TOLIMA' 'ANTIOQUIA' 'LA GUAJIRA'
 'CUNDINAMARCA' 'CAQUETA' 'CESAR' 'BOYACA' 'BOGOTA' 'SUCRE' 'NARIÑO'
 'MAGDALENA' 'ATLANTICO' 'CAUCA' 'SANTANDER' 'CORDOBA' 'NORTE SANTANDER'
 'QUINDIO' 'RISARALDA' 'PUTUMAYO' 'GUAVIARE' 'META' 'GUAINIA' 'CASANARE'
 'CALDAS' 'CHOCO' 'VAUPES' 'ARAUCA' 'SAN ANDRES' 'VICHADA' 'AMAZONAS']
----------------------------------------
Valores únicos en la columna 'cole_genero':
['MIXTO' 'FEMENINO' 'MASCULINO']
----------------------------------------
Valores únicos en la columna 'cole_jornada':
['MAÑANA' 'COMPLETA' 'TARDE' 'NOCHE' 'UNICA' 'SABATINA']
----------------------------------------
Valores únicos en la columna 'cole_naturaleza':
['OFICIAL' 'NO OFICIAL']
----------------------------------------
Valores únicos en la columna 'estu_genero':
['F' 'M' '15/07/2000' 'ESTUDIANTE' '24/07/2000' '26/11/1998' '06/09/1999'
 '22/01/1999' '18/08/1999' '31/07/2000' '15/12/1998' '10/04/2001'
 '08/10/2001' '20/11/2002' '18/08/2000' '27/08/1997' '28/08/1999'
 '18/02/1997' '22/03/2001' '02/05/2000' '25/09/2000' '15/01/2002'
 '01/10/1999' '12/07/1999' nan '11/03/2001' '09/05/2002' '22/01/2000'
 '27/03/1998' '14/05/2000' '05/08/2000' '26/05/1999' '07/11/1999'
 '12/04/2001' '17/04/1999' '09/09/2000' '29/09/2000' '08/08/1999'
 '22/11/2000' '10/03/1998' '12/08/1999' '05/10/1998' '03/12/2000'
 '26/01/2000' '10/07/1999' '24/05/2000' '22/10/2001' '17/11/2000'
 '05/08/1999' '11/12/2000' '29/05/2000' '24/08/2000' '24/06/2000'
 '13/04/2000' '21/05/1999' '03/09/1998' '09/10/1999' '25/03/2001'
 '03/12/1998' '12/10/2000' '27/12/1999' '27/06/1999' '20/02/2000'
 '18/11/1998' '23/07/1999' '21/04/2001' '07/12/1998' '08/01/2000'
 '05/09/2000' '20/05/1999' '11/03/1999' '08/06/2000' '11/10/2000'
 '25/12/2000' '22/10/2000' '13/08/1998' '29/12/2000' '15/03/2000'
 '23/06/2001' '13/05/1999' '29/06/2000' '24/05/2001' '03/04/1995'
 '02/04/2000' '23/03/2002' '08/04/1998' '23/12/2000' '14/11/2000'
 '04/03/1999' '23/02/2000' '21/11/1998' '22/07/1999' '28/04/2000'
 '29/04/2000' '13/03/2000' '21/09/1999' '03/12/1999' '09/10/1994'
 '07/11/2000' '07/09/1999' '25/12/1999' '08/05/1998' '21/10/1997'
 '10/09/2000' '27/03/1999' '30/03/1996' '27/02/2002' '16/06/2000']
----------------------------------------
Valores únicos en la columna 'estu_nacionalidad':
['COLOMBIA' 'VENEZUELA' 'CÓRDOBA' 'ESTADOS UNIDOS' 'CHINCHINÁ' 'LÍBANO'
 'ESPAÑA' 'ECUADOR' 'FRANCIA' 'DAGUA' 'NEIVA' 'BRASIL' 'GUATEMALA'
 'PARAGUAY' 'BOLIVIA' 'ARGENTINA' 'ITALIA' 'CHINA' 'COMORAS' 'PANAMÁ'
 'MÉXICO' 'CALI' 'RUSIA' 'CUBA' 'PERÚ' 'CHILE' 'COREA DEL SUR'
 'PAÍSES BAJOS - HOLANDA' 'IRÁN' 'SUIZA' 'COSTA RICA' 'ALEMANIA' 'NAURU'
 'JAPÓN' 'ARGELIA' 'DINAMARCA' 'COREA DEL NORTE' 'TERRITORIOS PALESTINOS'
 'REPÚBLICA DOMINICANA' 'NICARAGUA' 'BÉLGICA' 'REINO UNIDO' 'URUGUAY'
 'ALBANIA' 'NAMIBIA' 'AUSTRIA' 'BONAIRE' 'EL SALVADOR' 'HONDURAS'
 'CROACIA' 'PORTUGAL' 'UCRANIA' 'BIELORRUSIA' 'BULGARIA' 'ARUBA'
 'PUERTO RICO' 'TURQUÍA']
----------------------------------------
Valores únicos en la columna 'estu_pais_reside':
['COLOMBIA' 'VENEZUELA' 'ESTADOS UNIDOS' 'CHINCHINÁ' 'LÍBANO' 'ESPAÑA'
 'ECUADOR' 'FRANCIA' 'BRASIL' 'GUATEMALA' 'PARAGUAY' 'BOLIVIA' 'ARGENTINA'
 'ITALIA' 'CHINA' 'COMORAS' 'PANAMÁ' 'MÉXICO' 'RUSIA' 'CUBA' 'PERÚ'
 'CHILE' 'COREA DEL SUR' 'PAÍSES BAJOS - HOLANDA' 'IRÁN' 'SUIZA'
 'COSTA RICA' 'ALEMANIA' 'NAURU' 'JAPÓN' 'ARGELIA' 'DINAMARCA'
 'COREA DEL NORTE' 'TERRITORIOS PALESTINOS' 'REPÚBLICA DOMINICANA'
 'NICARAGUA' 'BÉLGICA' 'REINO UNIDO' 'URUGUAY' 'ALBANIA' 'NAMIBIA'
 'AUSTRIA' 'BONAIRE' 'EL SALVADOR' 'HONDURAS' 'CROACIA' 'PORTUGAL'
 'UCRANIA' 'BIELORRUSIA' 'BULGARIA' 'ARUBA' 'PUERTO RICO' 'TURQUÍA']
----------------------------------------
Valores únicos en la columna 'estu_privado_libertad':
['N' 'COLOMBIA' 'S']
----------------------------------------
Valores únicos en la columna 'fami_cuartoshogar':
['Dos' 'Tres' 'Cuatro' 'Seis o mas' 'Uno' 'Cinco' nan 'N' 'COLOMBIA']
----------------------------------------
Valores únicos en la columna 'fami_educacionmadre':
['Secundaria (Bachillerato) completa' 'Primaria completa'
 'Educación profesional completa' 'Secundaria (Bachillerato) incompleta'
 'Técnica o tecnológica completa' nan 'Primaria incompleta' 'Postgrado'
 'Ninguno' 'Técnica o tecnológica incompleta'
 'Educación profesional incompleta' 'No sabe' 'No Aplica' 'Dos' 'N'
 'Seis o mas' 'Tres' 'Cinco' 'Cuatro' 'Uno']
----------------------------------------
Valores únicos en la columna 'fami_educacionpadre':
['Secundaria (Bachillerato) incompleta' 'Primaria incompleta'
 'Técnica o tecnológica completa' 'Primaria completa'
 'Secundaria (Bachillerato) completa' nan
 'Técnica o tecnológica incompleta' 'Educación profesional completa'
 'Postgrado' 'No Aplica' 'No sabe' 'Ninguno'
 'Educación profesional incompleta' 'Dos' 'Cuatro' 'Uno' 'Tres']
----------------------------------------
Valores únicos en la columna 'fami_estratovivienda':
['Estrato 2' 'Estrato 1' 'Sin Estrato' 'Estrato 3' nan 'Estrato 4'
 'Estrato 5' 'Estrato 6' 'Secundaria (Bachillerato) completa'
 'Primaria completa' 'Educación profesional completa' 'No sabe'
 'Primaria incompleta' 'Ninguno' 'No Aplica'
 'Secundaria (Bachillerato) incompleta' 'Educación profesional incompleta'
 'Postgrado' 'Técnica o tecnológica incompleta'
 'Técnica o tecnológica completa']
----------------------------------------
Valores únicos en la columna 'fami_personashogar':
['5 a 6' '3 a 4' '1 a 2' '7 a 8' nan '9 o más' 'Estrato 1'
 'Primaria incompleta' 'Estrato 2' 'Secundaria (Bachillerato) completa'
 'Estrato 4' 'Estrato 3' 'Estrato 6' 'Ninguno' 'Sin Estrato'
 'Primaria completa' 'Estrato 5' 'Secundaria (Bachillerato) incompleta']
----------------------------------------
Valores únicos en la columna 'fami_tieneautomovil':
['No' 'Si' nan '5 a 6' 'Estrato 2' '3 a 4' '1 a 2' '9 o más' '7 a 8'
 'Estrato 3' 'Estrato 1']
----------------------------------------
Valores únicos en la columna 'fami_tienecomputador':
['No' 'Si' nan '3 a 4' '5 a 6' '1 a 2' '9 o más']
----------------------------------------
Valores únicos en la columna 'fami_tieneinternet':
['No' 'Si' nan]
----------------------------------------
Valores únicos en la columna 'fami_tienelavadora':
['Si' 'No' nan]
----------------------------------------
Valores únicos en la columna 'desemp_ingles':
['A-' 'A1' 'A2' 'B1' 'B+' 'Si' 'No' nan]
----------------------------------------
Valores únicos en la columna 'punt_ingles':
[ 45.  36.  48.  37.  56.  43.  35.  52.  53.  59.  60.  64.  54.  68.
  32.  88.  42.  40.  51.  49.  44.  77.  46.  69.  31.  58.  50.  65.
  55.  80.  57.  38.  39.  34.  63.  47.  30.  78.  62.  33.  71.  73.
  29.  61.  81.  67.  41.  83.  79.  66.  82.  27.  70.  75.  85.  26.
  72. 100.  76.  74.  87.  89.  nan  96.  28.  91.  84.  86.  92.  90.
  93.  97.   0.  25.  95.  99.  98.  94.  21.  24.  13.  23.  19.  16.
  14.  20.  18.  22.]
----------------------------------------
Valores únicos en la columna 'punt_matematicas':
[ 39.  50.  53.  52.  46.  65.  49.  51.  38.  42.  67.  70.  72.  58.
  59.  57.  44.  82.  48.  37.  47.  45.  41.  35.  30.  62.  63.  40.
  33.  55.  54.  75.  60.  29.  43.  64.  34.  32.  56.  36.  78.  69.
  61.  68.  74.  31.  66.  28.  23.  71.  73.  24.  25.  26.  85.  80.
  84.  27.  77.  76.  79. 100.  21.  22.  81.   0.  18.  83.  nan  20.
  19.  86.  88.  87.  89.  17.  92.  90.]
----------------------------------------
Valores únicos en la columna 'punt_sociales_ciudadanas':
[ 50  45  54  56  48  62  40  35  34  53  59  63  66  68  57  64  42  79
  36  49  65  43  47  44  37  46  55  51  60  61  38  41  58  39  70  32
  30  69  73  28  71  52  75  33  74  24  67  29  31  72  76  78  23  27
  80  77  81  26  25  83  82   0 100  22  20  21  88  19  18  86  84  85
  87]
----------------------------------------
Valores únicos en la columna 'punt_c_naturales':
[ 48  52  51  58  54  36  43  55  65  40  73  70  63  39  56  46  44  72
  41  60  59  42  50  57  61  47  69  49  35  30  62  38  32  45  33  66
  67  64  53  68  29  37  71  28  79  34  81  75  31  78  76  77  74  27
 100  80   0  82  26  25  83  24  84  23  85]
----------------------------------------
Valores únicos en la columna 'punt_lectura_critica':
[ 49  59  58  46  53  45  35  41  64  73  50  69  48  70  65  44  62  51
  42  63  75  60  61  55  52  71  67  43  66  47  72  57  36  39  56  38
  40  74  68  54  27  37  33  31  32  34  76  30  79  29  28  78  77  82
  80   0  83  81  84  26 100  25  24  85  23]
----------------------------------------
Valores únicos en la columna 'punt_global':
[232 235 270 268 292 238 240 180 201 279 310 297 352 315 312 226 381 318
 209 246 213 320 242 233 251 263 341 215 191 311 262 288 228 204 258 236
 298 252 304 290 371 260 177 223 250 227 190 239 307 277 205 319 220 282
 197 181 211 299 189 272 175 283 264 173 338 294 188 207 280 231 200 346
 357 218 344 273 222 254 303 314 293 221 195 302 210 243 206 182 219 313
 244 301 275 291 192 317 274 306 305 171 326 208 196 247 365 248 184 198
 327 266 257 234 199 330 269 185 289 355 214 300 316 212 358 286 230 287
 193 183 339 253 187 348 323 186 202 328 162 256 217 255 164 203 168 176
 245 382 178 296 387 325 261 308 259 265 395 165 229 281 342 172 278 324
 369 241 179 225 333 332 347 216 276 152 224 295 170 237 363 267 340 345
 322 321 284 329 353 364 337 167 396 309 350 368 249 367 194 351 271 377
 174 331 166 335 285 398 160 158 334 336 148 354 343 360 153 400 161 169
 390 361 402 155 384 362 157 366 372 378 150  45 388 375 356 393 418 144
  13 430 374 159 146 397 392 359 380 145 154 163 373 370 376 386 415 422
 151 349 389 394 434 379  41 140 433 383 385 147  65 156 149 408 403 411
 137 470 407 142 404 416 410 391 423 449  42 135 405 412 143  61 409 406
 440  49 141 419 438 421  70 399 131  90 442 401 126  47 414 128 426 445
 417 435  37 413 472 138 134 420 424  97 436 431 103 123  67 455  60 437
  46 450  50 107  52 428 129   0 127 113  71 465 122 125  53  43 441  44
 118 114 463 119 133 425 427 446  57  62 132 109 130 447 460 448  55 452
 106  64 104  59  23  56  51 444 453 454 139  73 105 432 459 476  36  30
 468  48 462 443 136  39  40  92  98  93  58 439 101  85 116 117 111  75
 124 100 108  38  94  96 112 429  69  54 457 471 451  81 110  68  32  34
 456]
----------------------------------------

In [293]:
# 1. Eliminar filas con 'cole_calendario' == "OTRO"
df = df[df['cole_calendario'] != "OTRO"]

In [294]:
# 2. Eliminar filas con 'cole_caracter' == "NO APLICA"
df = df[df['cole_caracter'] != "NO APLICA"]

In [295]:
# 3. Eliminar filas de la columna estu_genero cuyo valor NO sea 'F' o 'M'
df = df[df['estu_genero'].isin(['F', 'M'])]

In [296]:
# 4. Eliminar filas donde 'estu_pais_reside' no sea 'COLOMBIA'
df = df[df['estu_pais_reside'] == 'COLOMBIA']

In [297]:
# 5. En 'fami_educacionmadre', eliminar filas con valores no deseados
valores_no_madre = ['No sabe', 'No Aplica']
df = df[~df['fami_educacionmadre'].isin(valores_no_madre)]

In [298]:
# 6. En 'fami_educacionpadre', eliminar filas con valores no deseados
valores_no_padre = ['No Aplica', 'No sabe']
df = df[~df['fami_educacionpadre'].isin(valores_no_padre)]

In [299]:
# Saber el tipo de dato de cada columna, para corroborar que las columnas donde esta el puntaje global y el puntaje por competencias sea un int o float
print(df.dtypes)

periodo                       int64
estu_tipodocumento           object
cole_bilingue                object
cole_calendario              object
cole_caracter                object
cole_depto_ubicacion         object
cole_genero                  object
cole_jornada                 object
cole_naturaleza              object
estu_genero                  object
estu_nacionalidad            object
estu_pais_reside             object
estu_privado_libertad        object
fami_cuartoshogar            object
fami_educacionmadre          object
fami_educacionpadre          object
fami_estratovivienda         object
fami_personashogar           object
fami_tieneautomovil          object
fami_tienecomputador         object
fami_tieneinternet           object
fami_tienelavadora           object
desemp_ingles                object
punt_ingles                 float64
punt_matematicas            float64
punt_sociales_ciudadanas      int64
punt_c_naturales              int64
punt_lectura_critica          int64
punt_global                   int64
dtype: object

In [300]:
import pandas as pd

# Corroborar que los valores unicos de cada columna sean acordes al nombre de esa columna 
for column in df.columns:
    print(f"Valores únicos en la columna '{column}':")
    print(df[column].unique())
    print('-' * 40)

Valores únicos en la columna 'periodo':
[20172 20171]
----------------------------------------
Valores únicos en la columna 'estu_tipodocumento':
['CC' 'TI' 'CR' 'CE' 'RC' 'PC' 'PE' 'V' 'NUI' 'NUIP']
----------------------------------------
Valores únicos en la columna 'cole_bilingue':
[nan 'N' 'S']
----------------------------------------
Valores únicos en la columna 'cole_calendario':
['A' 'B']
----------------------------------------
Valores únicos en la columna 'cole_caracter':
['ACADÉMICO' 'TÉCNICO' 'TÉCNICO/ACADÉMICO' nan]
----------------------------------------
Valores únicos en la columna 'cole_depto_ubicacion':
['BOLIVAR' 'HUILA' 'VALLE' 'TOLIMA' 'ANTIOQUIA' 'LA GUAJIRA'
 'CUNDINAMARCA' 'CAQUETA' 'CESAR' 'BOYACA' 'BOGOTA' 'NARIÑO' 'MAGDALENA'
 'CAUCA' 'SUCRE' 'SANTANDER' 'CORDOBA' 'NORTE SANTANDER' 'QUINDIO'
 'ATLANTICO' 'RISARALDA' 'PUTUMAYO' 'GUAVIARE' 'META' 'GUAINIA' 'CASANARE'
 'CALDAS' 'CHOCO' 'VAUPES' 'ARAUCA' 'SAN ANDRES' 'VICHADA' 'AMAZONAS']
----------------------------------------
Valores únicos en la columna 'cole_genero':
['MIXTO' 'FEMENINO' 'MASCULINO']
----------------------------------------
Valores únicos en la columna 'cole_jornada':
['MAÑANA' 'COMPLETA' 'TARDE' 'NOCHE' 'UNICA' 'SABATINA']
----------------------------------------
Valores únicos en la columna 'cole_naturaleza':
['OFICIAL' 'NO OFICIAL']
----------------------------------------
Valores únicos en la columna 'estu_genero':
['F' 'M']
----------------------------------------
Valores únicos en la columna 'estu_nacionalidad':
['COLOMBIA']
----------------------------------------
Valores únicos en la columna 'estu_pais_reside':
['COLOMBIA']
----------------------------------------
Valores únicos en la columna 'estu_privado_libertad':
['N' 'S']
----------------------------------------
Valores únicos en la columna 'fami_cuartoshogar':
['Dos' 'Tres' 'Cuatro' 'Seis o mas' 'Uno' 'Cinco' nan]
----------------------------------------
Valores únicos en la columna 'fami_educacionmadre':
['Secundaria (Bachillerato) completa' 'Primaria completa'
 'Educación profesional completa' 'Secundaria (Bachillerato) incompleta'
 'Técnica o tecnológica completa' nan 'Primaria incompleta' 'Postgrado'
 'Ninguno' 'Técnica o tecnológica incompleta'
 'Educación profesional incompleta']
----------------------------------------
Valores únicos en la columna 'fami_educacionpadre':
['Secundaria (Bachillerato) incompleta' 'Primaria incompleta'
 'Técnica o tecnológica completa' 'Primaria completa'
 'Secundaria (Bachillerato) completa' nan
 'Técnica o tecnológica incompleta' 'Educación profesional completa'
 'Postgrado' 'Ninguno' 'Educación profesional incompleta']
----------------------------------------
Valores únicos en la columna 'fami_estratovivienda':
['Estrato 2' 'Estrato 1' 'Sin Estrato' 'Estrato 3' nan 'Estrato 4'
 'Estrato 5' 'Estrato 6']
----------------------------------------
Valores únicos en la columna 'fami_personashogar':
['5 a 6' '3 a 4' '1 a 2' '7 a 8' nan '9 o más']
----------------------------------------
Valores únicos en la columna 'fami_tieneautomovil':
['No' 'Si' nan]
----------------------------------------
Valores únicos en la columna 'fami_tienecomputador':
['No' 'Si' nan]
----------------------------------------
Valores únicos en la columna 'fami_tieneinternet':
['No' 'Si' nan]
----------------------------------------
Valores únicos en la columna 'fami_tienelavadora':
['Si' 'No' nan]
----------------------------------------
Valores únicos en la columna 'desemp_ingles':
['A-' 'A1' 'A2' 'B1' 'B+']
----------------------------------------
Valores únicos en la columna 'punt_ingles':
[ 45.  36.  48.  37.  56.  43.  35.  52.  53.  59.  60.  64.  68.  32.
  88.  42.  40.  44.  77.  46.  31.  58.  50.  49.  55.  80.  57.  38.
  39.  34.  63.  54.  47.  30.  78.  62.  71.  69.  73.  29.  61.  81.
  67.  65.  51.  33.  41.  83.  79.  66.  82.  27.  70.  75.  85.  26.
  72. 100.  74.  76.  87.  89.  96.  28.  91.  84.  86.  92.  90.  97.
   0.  25.  95.  99.  93.  98.  94.  24.  13.  23.  19.  16.  14.  21.
  20.  18.  22.]
----------------------------------------
Valores únicos en la columna 'punt_matematicas':
[ 39.  50.  53.  52.  46.  65.  49.  51.  38.  42.  67.  70.  72.  59.
  57.  44.  82.  48.  37.  47.  41.  35.  30.  62.  63.  40.  33.  58.
  54.  75.  60.  45.  55.  29.  43.  64.  32.  56.  36.  34.  78.  69.
  61.  68.  74.  31.  66.  23.  71.  73.  24.  28.  25.  85.  80.  84.
  27.  77.  76.  79. 100.  21.  26.  22.  81.   0.  18.  83.  20.  19.
  86.  88.  87.  89.  17.  90.]
----------------------------------------
Valores únicos en la columna 'punt_sociales_ciudadanas':
[ 50  45  54  56  48  62  40  35  34  53  59  63  66  57  64  42  79  36
  65  47  68  44  37  46  55  49  60  61  38  41  58  39  70  43  30  69
  73  28  71  52  75  51  33  74  24  67  29  31  32  72  76  78  23  27
  80  77  26  81  25  83   0 100  22  20  21  82  88  19  18  86  84  85
  87]
----------------------------------------
Valores únicos en la columna 'punt_c_naturales':
[ 48  52  51  58  54  36  43  55  65  40  73  70  39  56  46  44  72  41
  59  42  50  57  61  47  69  49  35  30  62  38  60  32  45  33  66  67
  64  53  68  63  29  37  71  79  34  81  75  31  28  78  76  77  74  27
 100  80   0  82  26  25  83  24  84  23  85]
----------------------------------------
Valores únicos en la columna 'punt_lectura_critica':
[ 49  59  58  46  53  45  35  41  64  73  50  69  48  70  44  65  51  42
  63  60  61  55  52  43  66  47  72  57  36  39  56  38  40  74  75  68
  67  54  62  37  33  32  31  34  76  71  30  79  29  28  77  82  27  80
   0  78  83  81  84  26 100  25  24  85  23]
----------------------------------------
Valores únicos en la columna 'punt_global':
[232 235 270 268 292 238 240 180 201 279 310 297 352 312 226 381 209 246
 213 320 242 251 263 341 215 191 311 262 288 228 204 258 236 252 304 290
 371 260 177 223 250 227 190 239 307 277 205 319 220 282 181 211 299 189
 272 175 283 264 173 338 294 188 280 231 200 346 357 218 344 273 222 254
 303 314 293 221 195 302 210 243 206 219 313 244 301 315 275 291 192 317
 233 274 306 305 171 326 208 196 247 365 248 184 198 327 266 257 234 199
 330 269 185 289 207 355 214 300 316 197 358 230 287 193 339 253 183 187
 348 323 186 202 162 256 217 203 168 298 212 176 245 382 296 387 325 261
 308 259 265 395 255 165 281 342 172 286 369 179 225 333 328 332 347 216
 276 178 152 224 295 241 237 363 267 340 345 322 321 284 170 182 329 278
 353 337 167 396 350 368 249 194 351 271 229 377 331 324 335 318 285 398
 160 158 334 336 367 148 309 354 343 360 153 400 161 174 390 155 169 384
 362 157 366 372 378 150 375 356 393 418 144  13 430 159 146 361 397 392
 359 380 145 154 163 166 373 370 376 364 386 415 422 151 164 349 389 374
 394 434 379 388 433 383 385 147  65 156 149 402 408 403 411 137 470 407
 142 404 140 416 410 391 423 449 135 405 412 143 409 406 440 141 419 438
 421 131  90 442 399 401 126 414 128 426 445 417 435 413 472 138 134 420
 424  97 436 431 123 455 437 450 107 428 129   0 127 113 465 122 125 118
 114 463 119 133 425 427 446 132 109 130 447 460 448  55 452 106 441 104
  23 444 453 454 103 139 105 432 459 476 468 462 443 136  92  98  93 439
 101 116 117 111 124 100 108  36  94  96 112 429  62 457 471 451  81  73
 110  67 456]
----------------------------------------

In [301]:
# Contar la cantidad de datos vacios en cada columna luego de filtrar el Dataframe
numero_datos_faltantes = df.isna().sum()

# Mostrar el resultado
print(numero_datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue               70142
cole_calendario                 0
cole_caracter                7573
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     0
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8344
fami_educacionmadre         24162
fami_educacionpadre         24204
fami_estratovivienda        26685
fami_personashogar          10901
fami_tieneautomovil          9937
fami_tienecomputador         8682
fami_tieneinternet          24924
fami_tienelavadora           8147
desemp_ingles                   0
punt_ingles                     0
punt_matematicas                0
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
dtype: int64

A partir de los datos que tenemos, queremos identificar relaciones entre las columnas que contienen datos completos y aquellas que tienen datos faltantes, con el fin de poder estimar y completar los valores ausentes en lugar de eliminar las filas incompletas.

In [302]:
df_copia_datos = df.copy()

In [303]:
import pandas as pd

# Crear los rangos de puntaje
rango_puntaje_global = [0, 20, 40, 60, 80, 100]
rango_labels = ['0-20', '20-40', '40-60', '60-80', '80-100']
df['rango_puntaje'] = pd.cut(df['punt_ingles'], bins=rango_puntaje_global, labels=rango_labels, right=False)

# Tabla cruzada: cuenta cuántos "S" y "N" hay por cada rango
tabla_cruzada = pd.crosstab(df['rango_puntaje'], df['cole_bilingue'])

# Convertimos a porcentaje sobre el total por fila (por rango)
tabla_porcentajes_puntaje_colegio_bilingue = tabla_cruzada.div(tabla_cruzada.sum(axis=1), axis=0).round(4) * 100

# Mostrar la tabla final
print(tabla_porcentajes_puntaje_colegio_bilingue)

cole_bilingue      N      S
rango_puntaje
0-20           76.92  23.08
20-40          98.55   1.45
40-60          98.87   1.13
60-80          97.59   2.41
80-100         74.36  25.64

In [333]:
#Al DataFrame se le agrega una columna llamada rango_puntaje, que asigna un rango basado en el puntaje de inglés.
rango_puntaje_global_ajustado = [-0.01] + rango_puntaje_global[1:]

df_copia_datos['rango_puntaje'] = pd.cut(
    df_copia_datos['punt_ingles'],
    bins=rango_puntaje_global_ajustado,
    labels=rango_labels,
    right=True  
)

In [334]:
def asignar_cole_bilingue_segun_puntaje(df, tabla_porcentajes, col_rango='rango_puntaje', col_obj='cole_bilingue', margen=5):
    # Crear una copia del DataFrame original para no modificarlo directamente
    df = df.copy()

    # Obtener la lista de categorías (valores posibles en la columna objetivo)
    categorias = tabla_porcentajes.columns.tolist()  
    
    # Iterar sobre cada rango de puntaje definido en el índice de la tabla de porcentajes
    for rango in tabla_porcentajes.index:
        # Guardar en un diccionario el porcentaje objetivo para cada categoría en este rango
        porcentaje_obj = tabla_porcentajes.loc[rango].to_dict()

        # Filtrar el DataFrame para quedarnos solo con las filas que pertenecen a este rango
        mask_rango = df[col_rango] == rango
        df_rango = df.loc[mask_rango]

        # Contar cuántas veces aparece cada categoría en la columna objetivo dentro de este rango
        conteo_actual = df_rango[col_obj].value_counts(dropna=True).to_dict()

        # Asegurar que todas las categorías estén presentes en el conteo, aunque sea con valor 0
        for cat in categorias:
            if cat not in conteo_actual:
                conteo_actual[cat] = 0

        # Obtener los índices de las filas donde la columna objetivo está vacía (NaN) para asignarles categoría
        idx_nan = df_rango[df_rango[col_obj].isna()].index.tolist()

        # Para cada fila con valor NaN en la columna objetivo, intentar asignar una categoría adecuada
        for idx in idx_nan:
            asignado = False

            # Ordenar las categorías según el porcentaje objetivo (de mayor a menor)
            orden_categorias = sorted(categorias, key=lambda x: porcentaje_obj[x], reverse=True)

            # Probar asignar cada categoría en orden hasta encontrar una que no supere el margen permitido de desviación
            for cat in orden_categorias:
                # Crear una copia temporal del conteo actual y sumar uno a la categoría que se está evaluando
                conteo_temp = conteo_actual.copy()
                conteo_temp[cat] += 1

                # Calcular el nuevo porcentaje temporal de cada categoría después de la asignación hipotética
                total_temp = sum(conteo_temp.values())
                porcentaje_temp = {k: (v / total_temp) * 100 for k, v in conteo_temp.items()}

                # Verificar si la desviación entre los porcentajes actuales y objetivos está dentro del margen permitido para todas las categorías
                desviacion_ok = all(abs(porcentaje_temp.get(k, 0) - porcentaje_obj[k]) <= margen for k in porcentaje_obj)

                # Si la desviación está dentro del margen, asignar esta categoría y actualizar el conteo actual
                if desviacion_ok:
                    df.at[idx, col_obj] = cat
                    conteo_actual = conteo_temp
                    asignado = True
                    break  # Salir del ciclo de categorías, porque ya se asignó una categoría válida

            # Si no se pudo asignar ninguna categoría que cumpla con el margen, asignar la categoría con mayor porcentaje objetivo por defecto
            if not asignado:
                cat = orden_categorias[0]
                df.at[idx, col_obj] = cat
                conteo_actual[cat] += 1

    # Retornar el DataFrame modificado con las asignaciones hechas
    return df

In [335]:
#Apliar la función
df_final = asignar_cole_bilingue_segun_puntaje(df_copia_datos, tabla_porcentajes_puntaje_colegio_bilingue)
df_final

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global,rango_puntaje
0,20172,CC,N,A,ACADÉMICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,F,...,No,Si,A-,45.0,39.0,50,48,49,232,40-60
1,20172,TI,N,A,ACADÉMICO,HUILA,MIXTO,COMPLETA,OFICIAL,M,...,No,Si,A-,36.0,50.0,45,48,49,235,20-40
2,20172,TI,N,A,TÉCNICO,VALLE,MIXTO,MAÑANA,OFICIAL,M,...,Si,Si,A1,48.0,53.0,54,52,59,270,40-60
3,20172,TI,N,A,TÉCNICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,M,...,No,Si,A-,45.0,52.0,56,51,58,268,40-60
4,20172,TI,N,A,TÉCNICO/ACADÉMICO,TOLIMA,MIXTO,MAÑANA,OFICIAL,F,...,Si,Si,A-,37.0,46.0,48,51,46,235,20-40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561281,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,55.0,49.0,51,52,55,260,40-60
561282,20172,TI,N,A,ACADÉMICO,CUNDINAMARCA,MIXTO,UNICA,OFICIAL,F,...,Si,Si,A1,54.0,53.0,54,59,64,286,40-60
561283,20172,TI,N,A,ACADÉMICO,CAUCA,MIXTO,MAÑANA,OFICIAL,F,...,No,Si,A2,58.0,64.0,61,67,71,326,40-60
561285,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,48.0,40.0,50,54,62,256,40-60
561286,20172,TI,N,A,ACADÉMICO,CESAR,MIXTO,TARDE,OFICIAL,M,...,Si,No,A-,47.0,55.0,47,59,63,277,40-60

In [336]:
#Validar en el DataFrame final la proporción de cada valor de la columna cole_bilingue dentro de cada rango de puntaje.
tabla_porcentajes_puntaje_colegio_bilingue_final = pd.crosstab(df_final['rango_puntaje'], df_final['cole_bilingue'])
tabla_porcentajes_puntaje_colegio_bilingue_final = tabla_porcentajes_puntaje_colegio_bilingue_final.div(tabla_porcentajes_puntaje_colegio_bilingue_final.sum(axis=1), axis=0).round(3) * 100

In [337]:
# Unir proporciones originales y finales en un solo DataFrame
comparacion_proporciones = pd.DataFrame({
    'Original_S': tabla_porcentajes_puntaje_colegio_bilingue['S'],
    'Original_N': tabla_porcentajes_puntaje_colegio_bilingue['N'],
    'Final_S': tabla_porcentajes_puntaje_colegio_bilingue_final['S'],
    'Final_N': tabla_porcentajes_puntaje_colegio_bilingue_final['N'],
})

# Calcular diferencia en puntos porcentuales
comparacion_proporciones['Diferencia_S'] = (comparacion_proporciones['Final_S'] - comparacion_proporciones['Original_S']).round(2)
comparacion_proporciones['Diferencia_N'] = (comparacion_proporciones['Final_N'] - comparacion_proporciones['Original_N']).round(2)

# Mostrar resultado
print(comparacion_proporciones)

               Original_S  Original_N  Final_S  Final_N  Diferencia_S  \
rango_puntaje
0-20                23.08       76.92     20.0     80.0         -3.08
20-40                1.45       98.55      1.2     98.8         -0.25
40-60                1.13       98.87      1.0     99.0         -0.13
60-80                2.41       97.59      2.5     97.5          0.09
80-100              25.64       74.36     27.0     73.0          1.36

               Diferencia_N
rango_puntaje
0-20                   3.08
20-40                  0.25
40-60                  0.13
60-80                 -0.09
80-100                -1.36

In [338]:
# Crear un diccionario donde cada clave es un valor de 'cole_bilingue'
# y el valor es una lista de estratos únicos asociados
estratos_por_bilingue = (
    df_final.groupby('cole_bilingue')['fami_estratovivienda']
    .unique()
    .apply(list)
    .to_dict()
)

# Mostrar el resultado
for bilingue, estratos in estratos_por_bilingue.items():
    print(f"{bilingue}: {estratos}")

N: ['Estrato 2', 'Estrato 1', 'Sin Estrato', 'Estrato 3', nan, 'Estrato 4', 'Estrato 5', 'Estrato 6']
S: ['Estrato 1', 'Estrato 4', 'Estrato 6', 'Estrato 5', 'Estrato 3', 'Estrato 2', nan, 'Sin Estrato']

In [345]:
# Contar la cantidad de valores vacios en cada columna
numero_datos_faltantes = df_final.isna().sum()

# Mostrar el resultado
print(numero_datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue                   0
cole_calendario                 0
cole_caracter                7573
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     0
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8344
fami_educacionmadre         24162
fami_educacionpadre         24204
fami_estratovivienda        26685
fami_personashogar          10901
fami_tieneautomovil          9937
fami_tienecomputador         8682
fami_tieneinternet          24924
fami_tienelavadora           8147
desemp_ingles                   0
punt_ingles                     0
punt_matematicas                0
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
dtype: int64

In [341]:
# Contar cuántas veces aparece cada valor de cole_bilingue en cada estrato
conteo = df.groupby(['fami_estratovivienda', 'cole_bilingue']).size().unstack(fill_value=0)

# Calcular el porcentaje que representa cada valor de cole_bilingue dentro de cada estrato
porcentaje_estrato_cole_bilingue_original = conteo.div(conteo.sum(axis=1), axis=0) * 100

# Redondear para mejor visualización
porcentaje_estrato_cole_bilingue_original = porcentaje_estrato_cole_bilingue_original.round(2)

# Mostrar el resultado
print(porcentaje_estrato_cole_bilingue_original)

cole_bilingue             N      S
fami_estratovivienda
Estrato 1             98.51   1.49
Estrato 2             99.16   0.84
Estrato 3             98.96   1.04
Estrato 4             95.38   4.62
Estrato 5             87.00  13.00
Estrato 6             71.11  28.89
Sin Estrato           96.51   3.49

In [342]:
# Contar cuántas veces aparece cada valor de cole_bilingue en cada estrato
conteo = df_final.groupby(['fami_estratovivienda', 'cole_bilingue']).size().unstack(fill_value=0)

# Calcular el porcentaje que representa cada valor de cole_bilingue dentro de cada estrato
porcentaje_estrato_cole_bilingue_final = conteo.div(conteo.sum(axis=1), axis=0) * 100

# Redondear para mejor visualización
porcentaje_estrato_cole_bilingue_final = porcentaje_estrato_cole_bilingue_final.round(2)

# Mostrar el resultado
print(porcentaje_estrato_cole_bilingue_final)

cole_bilingue             N      S
fami_estratovivienda
Estrato 1             98.73   1.27
Estrato 2             99.27   0.73
Estrato 3             99.08   0.92
Estrato 4             95.96   4.04
Estrato 5             88.51  11.49
Estrato 6             74.58  25.42
Sin Estrato           97.22   2.78

In [343]:
df_final

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global,rango_puntaje
0,20172,CC,N,A,ACADÉMICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,F,...,No,Si,A-,45.0,39.0,50,48,49,232,40-60
1,20172,TI,N,A,ACADÉMICO,HUILA,MIXTO,COMPLETA,OFICIAL,M,...,No,Si,A-,36.0,50.0,45,48,49,235,20-40
2,20172,TI,N,A,TÉCNICO,VALLE,MIXTO,MAÑANA,OFICIAL,M,...,Si,Si,A1,48.0,53.0,54,52,59,270,40-60
3,20172,TI,N,A,TÉCNICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,M,...,No,Si,A-,45.0,52.0,56,51,58,268,40-60
4,20172,TI,N,A,TÉCNICO/ACADÉMICO,TOLIMA,MIXTO,MAÑANA,OFICIAL,F,...,Si,Si,A-,37.0,46.0,48,51,46,235,20-40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561281,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,55.0,49.0,51,52,55,260,40-60
561282,20172,TI,N,A,ACADÉMICO,CUNDINAMARCA,MIXTO,UNICA,OFICIAL,F,...,Si,Si,A1,54.0,53.0,54,59,64,286,40-60
561283,20172,TI,N,A,ACADÉMICO,CAUCA,MIXTO,MAÑANA,OFICIAL,F,...,No,Si,A2,58.0,64.0,61,67,71,326,40-60
561285,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,48.0,40.0,50,54,62,256,40-60
561286,20172,TI,N,A,ACADÉMICO,CESAR,MIXTO,TARDE,OFICIAL,M,...,Si,No,A-,47.0,55.0,47,59,63,277,40-60

In [344]:
df_final = df_final.drop('rango_puntaje', axis=1)

In [346]:
df_final

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20172,CC,N,A,ACADÉMICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,F,...,No,No,Si,A-,45.0,39.0,50,48,49,232
1,20172,TI,N,A,ACADÉMICO,HUILA,MIXTO,COMPLETA,OFICIAL,M,...,No,No,Si,A-,36.0,50.0,45,48,49,235
2,20172,TI,N,A,TÉCNICO,VALLE,MIXTO,MAÑANA,OFICIAL,M,...,Si,Si,Si,A1,48.0,53.0,54,52,59,270
3,20172,TI,N,A,TÉCNICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,M,...,Si,No,Si,A-,45.0,52.0,56,51,58,268
4,20172,TI,N,A,TÉCNICO/ACADÉMICO,TOLIMA,MIXTO,MAÑANA,OFICIAL,F,...,Si,Si,Si,A-,37.0,46.0,48,51,46,235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561281,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A1,55.0,49.0,51,52,55,260
561282,20172,TI,N,A,ACADÉMICO,CUNDINAMARCA,MIXTO,UNICA,OFICIAL,F,...,Si,Si,Si,A1,54.0,53.0,54,59,64,286
561283,20172,TI,N,A,ACADÉMICO,CAUCA,MIXTO,MAÑANA,OFICIAL,F,...,Si,No,Si,A2,58.0,64.0,61,67,71,326
561285,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A1,48.0,40.0,50,54,62,256
561286,20172,TI,N,A,ACADÉMICO,CESAR,MIXTO,TARDE,OFICIAL,M,...,Si,Si,No,A-,47.0,55.0,47,59,63,277

In [347]:
df_copia_datos1 = df.copy(deep=True)

In [349]:
import pandas as pd
from itertools import product

# Filtrar solo colegios oficiales
df_colegio_oficial = df_copia_datos1[df_copia_datos1['cole_naturaleza'] == 'OFICIAL']

# Variables a analizar
cols = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']

# Subset con columnas relevantes
df_permutaciones = df_colegio_oficial[cols + ['desemp_ingles', 'fami_estratovivienda']]

# Contar la cantidad de veces que cada combinacion de las variables a analizar esta presente en el DataFrame y calcular su porcentaje 
conteo_combinaciones = df_permutaciones.value_counts(subset=cols).reset_index()
conteo_combinaciones.columns = cols + ['conteo']

total_conteo = conteo_combinaciones['conteo'].sum()
conteo_combinaciones['porcentaje'] = round((conteo_combinaciones['conteo'] / total_conteo) * 100, 2)

# Mostrar unicamente la columna de porcentaje 
porcentaje_df = conteo_combinaciones[cols + ['porcentaje']]

# Lista con frecuencia de desempeños en inglés
def frecuencia_desempeno(grupo):
    frec = grupo['desemp_ingles'].value_counts().sort_values(ascending=False)
    return ', '.join([f"{d}:{c}" for d, c in frec.items()])

desemp_freq = df_permutaciones.groupby(cols).apply(frecuencia_desempeno).reset_index(name='frecuencia_desemp_ingles')

# Lista con frecuencia de estratos 
def frecuencia_estratos(grupo):
    frec = grupo['fami_estratovivienda'].value_counts().sort_values(ascending=False)
    return ', '.join([f"{e}:{c}" for e, c in frec.items()])

estrato_freq = df_permutaciones.groupby(cols).apply(frecuencia_estratos).reset_index(name='frecuencia_estratos')

# Generar todas las combinaciones posibles de Si y No para las variables a analizar
combinaciones_posibles = list(product(['Si', 'No'], repeat=4))
df_combinaciones = pd.DataFrame(combinaciones_posibles, columns=cols)

# Unir los resultados
df_resultado_oficial = (
    df_combinaciones
    .merge(porcentaje_df, on=cols, how='left')
    .merge(desemp_freq, on=cols, how='left')
    .merge(estrato_freq, on=cols, how='left')
    .fillna({
        'porcentaje': 0,
        'frecuencia_desemp_ingles': 'Sin datos',
        'frecuencia_estratos': 'Sin datos'
    })
)

# Ordenar por porcentaje descendente 
df_resultado_oficial = df_resultado_oficial.sort_values(by='porcentaje', ascending=False).reset_index(drop=True)

# Mostrar resultado
print(df_resultado_oficial)

C:\Users\evivas\AppData\Local\Temp\ipykernel_5892\340451329.py:28: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  desemp_freq = df_permutaciones.groupby(cols).apply(frecuencia_desempeno).reset_index(name='frecuencia_desemp_ingles')
C:\Users\evivas\AppData\Local\Temp\ipykernel_5892\340451329.py:35: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  estrato_freq = df_permutaciones.groupby(cols).apply(frecuencia_estratos).reset_index(name='frecuencia_estratos')

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
0                    Si                 Si                  No
1                    No                 No                  No
2                    No                 No                  No
3                    Si                 Si                  Si
4                    Si                 No                  No
5                    No                 Si                  No
6                    Si                 Si                  No
7                    Si                 No                  No
8                    No                 Si                  No
9                    Si                 No                  Si
10                   No                 No                  Si
11                   No                 Si                  Si
12                   No                 No                  Si
13                   Si                 Si                  Si
14                   Si                 No                  Si
15                   No                 Si                  Si

   fami_tienelavadora  porcentaje  \
0                  Si       25.21
1                  Si       18.07
2                  No       16.73
3                  Si        9.63
4                  Si        7.42
5                  Si        5.87
6                  No        4.63
7                  No        3.82
8                  No        2.43
9                  Si        1.59
10                 Si        1.53
11                 Si        0.91
12                 No        0.83
13                 No        0.71
14                 No        0.43
15                 No        0.19

                         frecuencia_desemp_ingles  \
0   A-:36894, A1:30825, A2:16093, B1:5686, B+:714
1      A-:41743, A1:17456, A2:4537, B1:845, B+:79
2      A-:39250, A1:15667, A2:4157, B1:733, B+:75
3    A-:12210, A1:11337, A2:7295, B1:3091, B+:519
4       A-:14387, A1:8532, A2:2947, B1:643, B+:53
5       A-:11013, A1:6486, A2:2705, B1:709, B+:75
6        A-:7693, A1:5318, A2:2616, B1:850, B+:87
7        A-:7561, A1:4237, A2:1508, B1:329, B+:30
8         A-:5190, A1:2390, A2:883, B1:218, B+:28
9         A-:2991, A1:1832, A2:658, B1:188, B+:16
10         A-:3463, A1:1450, A2:448, B1:89, B+:10
11        A-:1579, A1:1021, A2:475, B1:150, B+:14
12           A-:2043, A1:716, A2:178, B1:26, B+:3
13         A-:1214, A1:764, A2:404, B1:152, B+:16
14            A-:904, A1:458, A2:150, B1:33, B+:7
15             A-:427, A1:170, A2:80, B1:19, B+:1

                                  frecuencia_estratos
0   Estrato 2:43180, Estrato 3:22113, Estrato 1:20...
1   Estrato 1:36503, Estrato 2:18631, Estrato 3:46...
2   Estrato 1:37977, Estrato 2:13518, Sin Estrato:...
3   Estrato 2:14548, Estrato 3:12236, Estrato 1:44...
4   Estrato 1:11707, Estrato 2:10271, Estrato 3:29...
5   Estrato 2:9049, Estrato 1:6606, Estrato 3:3681...
6   Estrato 2:7571, Estrato 1:5567, Estrato 3:2537...
7   Estrato 1:7227, Estrato 2:4453, Estrato 3:949,...
8   Estrato 2:3245, Estrato 1:3137, Estrato 3:1231...
9   Estrato 2:2550, Estrato 1:1811, Estrato 3:856,...
10  Estrato 1:2312, Estrato 2:2092, Estrato 3:627,...
11  Estrato 2:1439, Estrato 3:788, Estrato 1:708, ...
12  Estrato 1:1562, Estrato 2:861, Sin Estrato:227...
13  Estrato 2:1114, Estrato 1:603, Estrato 3:552, ...
14  Estrato 1:689, Estrato 2:552, Estrato 3:146, S...
15  Estrato 2:299, Estrato 1:205, Estrato 3:96, Si...

In [351]:
# Filtrar solo colegios oficiales
df_colegio_nooficial = df_copia_datos1[df_copia_datos1['cole_naturaleza'] == 'NO OFICIAL']

# Variables a analizar
cols = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']

# Subset con columnas relevantes
df_permutaciones = df_colegio_nooficial[cols + ['desemp_ingles', 'fami_estratovivienda']]

# Contar la cantidad de veces que cada combinacion de las variables a analizar esta presente en el DataFrame y calcular su porcentaje 
conteo_combinaciones = df_permutaciones.value_counts(subset=cols).reset_index()
conteo_combinaciones.columns = cols + ['conteo']

total_conteo = conteo_combinaciones['conteo'].sum()
conteo_combinaciones['porcentaje'] = round((conteo_combinaciones['conteo'] / total_conteo) * 100, 2)

# Mostrar unicamente la columna de porcentaje 
porcentaje_df = conteo_combinaciones[cols + ['porcentaje']]

# Lista con frecuencia de desempeños en inglés
def frecuencia_desempeno(grupo):
    frec = grupo['desemp_ingles'].value_counts().sort_values(ascending=False)
    return ', '.join([f"{d}:{c}" for d, c in frec.items()])

desemp_freq = df_permutaciones.groupby(cols).apply(frecuencia_desempeno).reset_index(name='frecuencia_desemp_ingles')

# Lista con frecuencia de estratos 
def frecuencia_estratos(grupo):
    frec = grupo['fami_estratovivienda'].value_counts().sort_values(ascending=False)
    return ', '.join([f"{e}:{c}" for e, c in frec.items()])

estrato_freq = df_permutaciones.groupby(cols).apply(frecuencia_estratos).reset_index(name='frecuencia_estratos')

# Generar todas las combinaciones posibles de Si y No para las variables a analizar
combinaciones_posibles = list(product(['Si', 'No'], repeat=4))
df_combinaciones = pd.DataFrame(combinaciones_posibles, columns=cols)

# Unir los resultados
df_resultado_nooficial = (
    df_combinaciones
    .merge(porcentaje_df, on=cols, how='left')
    .merge(desemp_freq, on=cols, how='left')
    .merge(estrato_freq, on=cols, how='left')
    .fillna({
        'porcentaje': 0,
        'frecuencia_desemp_ingles': 'Sin datos',
        'frecuencia_estratos': 'Sin datos'
    })
)

# Ordenar por porcentaje descendente 
df_resultado_nooficial = df_resultado_nooficial.sort_values(by='porcentaje', ascending=False).reset_index(drop=True)

# Mostrar resultado
print(df_resultado_nooficial)

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
0                    Si                 Si                  Si
1                    Si                 Si                  No
2                    No                 No                  No
3                    No                 No                  No
4                    No                 Si                  No
5                    Si                 Si                  No
6                    Si                 No                  No
7                    No                 Si                  No
8                    No                 Si                  Si
9                    Si                 No                  Si
10                   Si                 No                  No
11                   Si                 Si                  Si
12                   No                 No                  Si
13                   No                 No                  Si
14                   Si                 No                  Si
15                   No                 Si                  Si

   fami_tienelavadora  porcentaje  \
0                  Si       41.59
1                  Si       28.07
2                  Si        6.37
3                  No        4.83
4                  Si        4.45
5                  No        3.35
6                  Si        3.32
7                  No        1.53
8                  Si        1.39
9                  Si        1.33
10                 No        1.22
11                 No        0.97
12                 Si        0.89
13                 No        0.31
14                 No        0.19
15                 No        0.18

                         frecuencia_desemp_ingles  \
0   B1:13151, A2:12224, A1:9946, B+:8480, A-:7385
1    A-:10673, A1:9624, A2:7843, B1:4990, B+:1416
2         A-:5058, A1:1835, A2:652, B1:252, B+:47
3         A-:4166, A1:1182, A2:399, B1:167, B+:28
4         A-:2718, A1:1503, A2:800, B1:378, B+:73
5         A-:1701, A1:1162, A2:779, B1:403, B+:82
6         A-:2148, A1:1061, A2:576, B1:254, B+:53
7          A-:1050, A1:442, A2:265, B1:116, B+:16
8           A-:602, A1:468, A2:370, B1:227, B+:46
9           A-:652, A1:450, A2:284, B1:195, B+:60
10           A-:832, A1:413, A2:162, B1:74, B+:20
11          A-:386, A1:280, A2:254, B1:204, B+:72
12           A-:625, A1:274, A2:144, B1:42, B+:16
13              A-:287, A1:56, A2:22, B1:14, B+:4
14              A-:143, A1:48, A2:18, B1:16, B+:3
15              A-:109, A1:60, A2:30, B1:20, B+:6

                                  frecuencia_estratos
0   Estrato 3:19177, Estrato 4:11734, Estrato 2:87...
1   Estrato 2:13679, Estrato 3:13380, Estrato 1:37...
2   Estrato 1:3338, Estrato 2:3074, Estrato 3:913,...
3   Estrato 1:3221, Estrato 2:1882, Estrato 3:392,...
4   Estrato 2:2421, Estrato 3:1445, Estrato 1:1128...
5   Estrato 2:1894, Estrato 3:1007, Estrato 1:950,...
6   Estrato 2:1698, Estrato 1:1203, Estrato 3:861,...
7   Estrato 2:795, Estrato 1:494, Estrato 3:386, E...
8   Estrato 3:655, Estrato 2:585, Estrato 4:193, E...
9   Estrato 2:580, Estrato 3:519, Estrato 1:261, E...
10  Estrato 2:647, Estrato 1:556, Estrato 3:181, S...
11  Estrato 3:426, Estrato 2:403, Estrato 4:161, E...
12  Estrato 2:474, Estrato 1:304, Estrato 3:229, E...
13  Estrato 1:175, Estrato 2:133, Estrato 3:39, Si...
14  Estrato 2:92, Estrato 1:58, Estrato 3:41, Estr...
15  Estrato 2:97, Estrato 3:55, Estrato 1:39, Estr...

C:\Users\evivas\AppData\Local\Temp\ipykernel_5892\2899624839.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  desemp_freq = df_permutaciones.groupby(cols).apply(frecuencia_desempeno).reset_index(name='frecuencia_desemp_ingles')
C:\Users\evivas\AppData\Local\Temp\ipykernel_5892\2899624839.py:32: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  estrato_freq = df_permutaciones.groupby(cols).apply(frecuencia_estratos).reset_index(name='frecuencia_estratos')

In [353]:
import numpy as np
# Crear una copia filtrada de los oficiales
data_colegio_oficial = df_final[df_final['cole_naturaleza'].str.upper() == 'OFICIAL'].copy()

# Columnas a completar
cols_a_completar = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']
np.random.seed(42)
# Llenar valores nulos aleatoriamente
for col in cols_a_completar:
    mask = data_colegio_oficial[col].isna()
    n_missing = mask.sum()
    data_colegio_oficial.loc[mask, col] = np.random.choice(['Si', 'No'], size=n_missing)

In [ ]:
#Evaluamos si al llenar las columnas con valores aleatorios para los datos con colegio oficial si se respetan los porcentajes calculados para cada combinación
# Columnas a analizar
cols = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']

# Contar combinaciones
conteo_combinaciones_oficial = data_colegio_oficial.groupby(cols).size().reset_index(name='cantidad')

# Calcular porcentaje
total = conteo_combinaciones_oficial['cantidad'].sum()
conteo_combinaciones_oficial['porcentaje'] = (conteo_combinaciones_oficial['cantidad'] / total) * 100

# Ordenar por porcentaje de mayor a menor
conteo_combinaciones_oficial = conteo_combinaciones_oficial.sort_values(by='porcentaje', ascending=False)

print(conteo_combinaciones_oficial)

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
13                   Si                 Si                  No
1                    No                 No                  No
0                    No                 No                  No
15                   Si                 Si                  Si
9                    Si                 No                  No
5                    No                 Si                  No
12                   Si                 Si                  No
8                    Si                 No                  No
4                    No                 Si                  No
11                   Si                 No                  Si
3                    No                 No                  Si
7                    No                 Si                  Si
2                    No                 No                  Si
14                   Si                 Si                  Si
10                   Si                 No                  Si
6                    No                 Si                  Si

   fami_tienelavadora  cantidad  porcentaje
13                 Si     92949   24.371883
1                  Si     67389   17.669871
0                  No     62340   16.345987
15                 Si     35720    9.366036
9                  Si     29317    7.687124
5                  Si     23453    6.149542
12                 No     17676    4.634772
8                  No     14822    3.886433
4                  No     10913    2.861466
11                 Si      6901    1.809491
3                  Si      6237    1.635385
7                  Si      3828    1.003729
2                  No      3485    0.913792
14                 No      3103    0.813628
10                 No      2124    0.556928
6                  No      1121    0.293934

In [ ]:
#Se extraen las columnas en común entre las dos tablas de porcentajes, considerando únicamente los colegios oficiales.
tabla1_reducida_oficial = conteo_combinaciones_oficial[['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 
                          'fami_tienelavadora', 'porcentaje']].copy()

tabla2_reducida_oficial = df_resultado_oficial[['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 
                          'fami_tienelavadora', 'porcentaje']].copy()

In [ ]:
#Combinamos ambas tablas
comparacion_oficial = tabla1_reducida_oficial.merge(
    tabla2_reducida_oficial,
    on=['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora'],
    suffixes=('_1', '_2'),
    how='inner'  
)
# Calcular la diferencia porcentual absoluta
comparacion_oficial['diferencia_porcentual'] = abs(comparacion_oficial['porcentaje_1'] - comparacion_oficial['porcentaje_2'])

# Mostrar los resultados
print(comparacion_oficial[['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil',
                   'fami_tienelavadora', 'porcentaje_1', 'porcentaje_2', 'diferencia_porcentual']])

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
0                    Si                 Si                  No
1                    No                 No                  No
2                    No                 No                  No
3                    Si                 Si                  Si
4                    Si                 No                  No
5                    No                 Si                  No
6                    Si                 Si                  No
7                    Si                 No                  No
8                    No                 Si                  No
9                    Si                 No                  Si
10                   No                 No                  Si
11                   No                 Si                  Si
12                   No                 No                  Si
13                   Si                 Si                  Si
14                   Si                 No                  Si
15                   No                 Si                  Si

   fami_tienelavadora  porcentaje_1  porcentaje_2  diferencia_porcentual
0                  Si     24.371883         25.21               0.838117
1                  Si     17.669871         18.07               0.400129
2                  No     16.345987         16.73               0.384013
3                  Si      9.366036          9.63               0.263964
4                  Si      7.687124          7.42               0.267124
5                  Si      6.149542          5.87               0.279542
6                  No      4.634772          4.63               0.004772
7                  No      3.886433          3.82               0.066433
8                  No      2.861466          2.43               0.431466
9                  Si      1.809491          1.59               0.219491
10                 Si      1.635385          1.53               0.105385
11                 Si      1.003729          0.91               0.093729
12                 No      0.913792          0.83               0.083792
13                 No      0.813628          0.71               0.103628
14                 No      0.556928          0.43               0.126928
15                 No      0.293934          0.19               0.103934

In [358]:
# Crear una copia filtrada de los colegios no oficiales
data_colegios_nooficial = df_final[df_final['cole_naturaleza'].str.upper() == 'NO OFICIAL'].copy()

# Columnas a completar
cols_a_completar = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']
np.random.seed(42)
# Llenar valores nulos aleatoriamente
for col in cols_a_completar:
    mask = data_colegios_nooficial[col].isna()
    n_missing = mask.sum()
    data_colegios_nooficial.loc[mask, col] = np.random.choice(['Si', 'No'], size=n_missing)

In [359]:
# Columnas a analizar
cols = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']
# Contar combinaciones
conteo_combinaciones_nooficial = data_colegios_nooficial.groupby(cols).size().reset_index(name='cantidad')
# Calcular porcentaje
total = conteo_combinaciones_nooficial['cantidad'].sum()
conteo_combinaciones_nooficial['porcentaje'] = (conteo_combinaciones_nooficial['cantidad'] / total) * 100
# Ordenar por cantidad (opcional)
conteo_combinaciones_nooficial = conteo_combinaciones_nooficial.sort_values(by='porcentaje', ascending=False)
print(conteo_combinaciones_nooficial)

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
15                   Si                 Si                  Si
13                   Si                 Si                  No
1                    No                 No                  No
0                    No                 No                  No
5                    No                 Si                  No
9                    Si                 No                  No
12                   Si                 Si                  No
11                   Si                 No                  Si
4                    No                 Si                  No
7                    No                 Si                  Si
8                    Si                 No                  No
14                   Si                 Si                  Si
3                    No                 No                  Si
2                    No                 No                  Si
10                   Si                 No                  Si
6                    No                 Si                  Si

   fami_tienelavadora  cantidad  porcentaje
15                 Si     52145   39.800482
13                 Si     35563   27.144013
1                  Si      8470    6.464859
0                  No      6407    4.890242
5                  Si      6108    4.662026
9                  Si      5028    3.837699
12                 No      4504    3.437748
11                 Si      2443    1.864658
4                  No      2439    1.861605
7                  Si      1997    1.524241
8                  No      1817    1.386854
14                 No      1431    1.092233
3                  Si      1337    1.020486
2                  No       513    0.391555
10                 No       408    0.311412
6                  No       406    0.309886

In [360]:
#Se extraen las columnas en común entre las dos tablas de porcentajes, considerando únicamente los colegios no oficiales.
tabla1_reducida_nooficial = conteo_combinaciones_nooficial[['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 
                          'fami_tienelavadora', 'porcentaje']].copy()

tabla2_reducida_nooficial = df_resultado_nooficial[['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 
                          'fami_tienelavadora', 'porcentaje']].copy()

In [361]:
# Hacemos el merge con sufijos para distinguir los porcentajes
comparacion_nooficial = tabla1_reducida_nooficial.merge(
    tabla2_reducida_nooficial,
    on=['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora'],
    suffixes=('_1', '_2'),
    how='inner'  # solo combinaciones que existen en ambas
)

# Calcular la diferencia porcentual absoluta
comparacion_nooficial['diferencia_porcentual'] = abs(comparacion_nooficial['porcentaje_1'] - comparacion_nooficial['porcentaje_2'])

# Mostrar los resultados
print(comparacion_nooficial[['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil',
                   'fami_tienelavadora', 'porcentaje_1', 'porcentaje_2', 'diferencia_porcentual']])

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
0                    Si                 Si                  Si
1                    Si                 Si                  No
2                    No                 No                  No
3                    No                 No                  No
4                    No                 Si                  No
5                    Si                 No                  No
6                    Si                 Si                  No
7                    Si                 No                  Si
8                    No                 Si                  No
9                    No                 Si                  Si
10                   Si                 No                  No
11                   Si                 Si                  Si
12                   No                 No                  Si
13                   No                 No                  Si
14                   Si                 No                  Si
15                   No                 Si                  Si

   fami_tienelavadora  porcentaje_1  porcentaje_2  diferencia_porcentual
0                  Si     39.800482         41.59               1.789518
1                  Si     27.144013         28.07               0.925987
2                  Si      6.464859          6.37               0.094859
3                  No      4.890242          4.83               0.060242
4                  Si      4.662026          4.45               0.212026
5                  Si      3.837699          3.32               0.517699
6                  No      3.437748          3.35               0.087748
7                  Si      1.864658          1.33               0.534658
8                  No      1.861605          1.53               0.331605
9                  Si      1.524241          1.39               0.134241
10                 No      1.386854          1.22               0.166854
11                 No      1.092233          0.97               0.122233
12                 Si      1.020486          0.89               0.130486
13                 No      0.391555          0.31               0.081555
14                 No      0.311412          0.19               0.121412
15                 No      0.309886          0.18               0.129886

In [362]:
df_final1 = pd.concat([data_colegio_oficial, data_colegios_nooficial], ignore_index=True)
df_final1

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20172,CC,N,A,ACADÉMICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,F,...,No,No,Si,A-,45.0,39.0,50,48,49,232
1,20172,TI,N,A,ACADÉMICO,HUILA,MIXTO,COMPLETA,OFICIAL,M,...,No,No,Si,A-,36.0,50.0,45,48,49,235
2,20172,TI,N,A,TÉCNICO,VALLE,MIXTO,MAÑANA,OFICIAL,M,...,Si,Si,Si,A1,48.0,53.0,54,52,59,270
3,20172,TI,N,A,TÉCNICO,BOLIVAR,MIXTO,MAÑANA,OFICIAL,M,...,Si,No,Si,A-,45.0,52.0,56,51,58,268
4,20172,TI,N,A,TÉCNICO/ACADÉMICO,TOLIMA,MIXTO,MAÑANA,OFICIAL,F,...,Si,Si,Si,A-,37.0,46.0,48,51,46,235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512389,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A2,65.0,50.0,50,46,54,256
512390,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,MAÑANA,NO OFICIAL,M,...,Si,Si,Si,B1,68.0,71.0,70,65,66,340
512391,20172,CC,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,SABATINA,NO OFICIAL,F,...,Si,Si,Si,A-,39.0,34.0,39,38,49,200
512392,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A1,55.0,49.0,51,52,55,260
512393,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A1,48.0,40.0,50,54,62,256

In [363]:
# Contar la cantidad de valores faltantes en cada columna
numero_datos_faltantes = df_final1.isna().sum()

# Mostrar el resultado
print(numero_datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue                   0
cole_calendario                 0
cole_caracter                7573
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     0
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8344
fami_educacionmadre         24162
fami_educacionpadre         24204
fami_estratovivienda        26685
fami_personashogar          10901
fami_tieneautomovil             0
fami_tienecomputador            0
fami_tieneinternet              0
fami_tienelavadora              0
desemp_ingles                   0
punt_ingles                     0
punt_matematicas                0
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
dtype: int64

In [365]:
# Función para convertir un string con formato 'clave: valor, clave: valor' en un diccionario {clave: int(valor)}
def parse_estratos(s):
    pares = s.split(',')  # Separar el string por comas para obtener cada par clave:valor
    d = {}
    for par in pares:
        par = par.strip()  # Eliminar espacios en blanco alrededor del par clave:valor
        if ':' in par:
            clave, valor = par.split(':')  # Separar clave y valor por los dos puntos
            d[clave.strip()] = int(valor.strip())  # Guardar en el diccionario la clave con valor entero
    return d

# Aplicar la función anterior a la columna 'frecuencia_estratos' para crear una nueva columna con diccionarios
df_resultado_oficial['estratos_dict'] = df_resultado_oficial['frecuencia_estratos'].apply(parse_estratos)

# Función para calcular el porcentaje que representa cada valor respecto al total de su diccionario
def dict_to_pct(d):
    total = sum(d.values())  # Sumar todos los valores del diccionario para obtener el total
    return {k: (v / total) * 100 for k, v in d.items()}  # Calcular el porcentaje de cada valor

# Aplicar la función de porcentaje a la columna de diccionarios y expandir el resultado en columnas separadas
df_pct = df_resultado_oficial['estratos_dict'].apply(dict_to_pct).apply(pd.Series).fillna(0)

# Unir el DataFrame original (sin las columnas originales de strings y diccionarios) con el DataFrame de porcentajes
df_resultado_oficial_estratos = pd.concat(
    [df_resultado_oficial.drop(columns=['frecuencia_estratos', 'estratos_dict']), df_pct], axis=1
)

# Mostrar el DataFrame resultante con las columnas de porcentajes por estrato
print(df_resultado_oficial_estratos)

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
0                    Si                 Si                  No
1                    No                 No                  No
2                    No                 No                  No
3                    Si                 Si                  Si
4                    Si                 No                  No
5                    No                 Si                  No
6                    Si                 Si                  No
7                    Si                 No                  No
8                    No                 Si                  No
9                    Si                 No                  Si
10                   No                 No                  Si
11                   No                 Si                  Si
12                   No                 No                  Si
13                   Si                 Si                  Si
14                   Si                 No                  Si
15                   No                 Si                  Si

   fami_tienelavadora  porcentaje  \
0                  Si       25.21
1                  Si       18.07
2                  No       16.73
3                  Si        9.63
4                  Si        7.42
5                  Si        5.87
6                  No        4.63
7                  No        3.82
8                  No        2.43
9                  Si        1.59
10                 Si        1.53
11                 Si        0.91
12                 No        0.83
13                 No        0.71
14                 No        0.43
15                 No        0.19

                         frecuencia_desemp_ingles  Estrato 2  Estrato 3  \
0   A-:36894, A1:30825, A2:16093, B1:5686, B+:714  48.168848  24.667849
1      A-:41743, A1:17456, A2:4537, B1:845, B+:79  29.066430   7.190552
2      A-:39250, A1:15667, A2:4157, B1:733, B+:75  22.781738   4.359843
3    A-:12210, A1:11337, A2:7295, B1:3091, B+:519  42.495764  35.742245
4       A-:14387, A1:8532, A2:2947, B1:643, B+:53  38.999848  11.125456
5       A-:11013, A1:6486, A2:2705, B1:709, B+:75  43.599133  17.735485
6        A-:7693, A1:5318, A2:2616, B1:850, B+:87  46.133691  15.459143
7        A-:7561, A1:4237, A2:1508, B1:329, B+:30  32.868320   7.004724
8         A-:5190, A1:2390, A2:883, B1:218, B+:28  37.789682  14.335624
9         A-:2991, A1:1832, A2:658, B1:188, B+:16  45.228805  15.182689
10         A-:3463, A1:1450, A2:448, B1:89, B+:10  38.704903  11.600370
11        A-:1579, A1:1021, A2:475, B1:150, B+:14  44.898596  24.586583
12           A-:2043, A1:716, A2:178, B1:26, B+:3  29.435897   6.324786
13         A-:1214, A1:764, A2:404, B1:152, B+:16  44.153785  21.878716
14            A-:904, A1:458, A2:150, B1:33, B+:7  35.960912   9.511401
15             A-:427, A1:170, A2:80, B1:19, B+:1  43.713450  14.035088

    Estrato 1  Estrato 4  Sin Estrato  Estrato 5  Estrato 6
0   23.062593   2.453064     0.843345   0.536573   0.267729
1   56.948735   1.391619     4.271584   0.659927   0.471154
2   64.002225   1.152738     6.769806   0.525810   0.407840
3   13.124379   6.233569     0.715663   1.232693   0.455687
4   44.452461   1.579587     2.665553   0.717649   0.459447
5   31.828475   2.635510     2.139244   1.175620   0.886533
6   33.922369   1.681799     1.578210   0.694656   0.530132
7   53.343667   1.350753     4.273694   0.723354   0.435489
8   36.531967   3.575172     3.621754   2.480494   1.665308
9   32.121320   3.086201     2.695991   0.975523   0.709471
10  42.775208   2.146161     3.533765   0.666050   0.573543
11  22.090484   3.868955     2.184087   1.716069   0.655226
12  53.401709   1.572650     7.760684   1.059829   0.444444
13  23.900119   4.122077     2.457392   1.823226   1.664685
14  44.885993   2.214984     4.495114   1.628664   1.302932
15  29.970760   4.093567     4.239766   2.046784   1.900585

In [372]:
def asignar_estrato_oficial(grupo):
    # Obtener la combinación actual del grupo (nombre del grupo, que es una tupla)
    combo = grupo.name  
    # Total de filas en este grupo
    total = len(grupo)
    
    # Filtrar la fila correspondiente en df_resultado_oficial_estratos
    # Según la combinación exacta de las cuatro variables indicadas
    filtro = (
        (df_resultado_oficial_estratos['fami_tienecomputador'] == combo[0]) &
        (df_resultado_oficial_estratos['fami_tieneinternet'] == combo[1]) &
        (df_resultado_oficial_estratos['fami_tieneautomovil'] == combo[2]) &
        (df_resultado_oficial_estratos['fami_tienelavadora'] == combo[3])
    )
    
    # Extraer la fila con los porcentajes de estratos para esta combinación
    fila_estratos = df_resultado_oficial_estratos.loc[filtro]
    if fila_estratos.empty:
        # Si no se encuentra la combinación, retornar el grupo sin cambios
        return grupo  

    # Obtener los porcentajes objetivo de estratos de la fila encontrada,
    # seleccionando solo columnas que contienen la palabra 'Estrato' y convirtiendo a float
    porcentajes_obj = fila_estratos.iloc[0].filter(like='Estrato').astype(float)
    estratos_disponibles = porcentajes_obj.index.tolist()

    # Separar las filas que ya tienen estrato asignado de las que no
    asignados = grupo[grupo['fami_estratovivienda'].notna()]
    sin_asignar = grupo[grupo['fami_estratovivienda'].isna()]
    n_sin_asignar = len(sin_asignar)

    # Calcular el conteo actual de estratos ya asignados y convertir a porcentaje del total
    conteo_actual = asignados['fami_estratovivienda'].value_counts()
    porcentaje_actual = (conteo_actual / total) * 100
    
    # Calcular cuánto porcentaje falta asignar para cada estrato,
    # rellenando con 0 si algún estrato no está presente en conteo_actual
    porcentaje_faltante = porcentajes_obj - porcentaje_actual.reindex(porcentajes_obj.index, fill_value=0)
    porcentaje_faltante = porcentaje_faltante.clip(lower=0)  # No permitir valores negativos

    # Calcular cuántas filas hay que asignar a cada estrato según el porcentaje faltante
    filas_por_asignar = (porcentaje_faltante * total / 100).round().astype(int)
    # Ajustar la diferencia en caso de que la suma no coincida con el número de filas por asignar
    diferencia = n_sin_asignar - filas_por_asignar.sum()

    if diferencia != 0:
        # Ajustar la asignación sumando o restando a la categoría con mayor porcentaje faltante
        estrato_ajuste = filas_por_asignar.idxmax()
        filas_por_asignar[estrato_ajuste] += diferencia

    # Construir la lista de asignaciones con la cantidad determinada para cada estrato
    asignaciones = []
    for estrato, cantidad in filas_por_asignar.items():
        asignaciones.extend([estrato] * cantidad)

    # Ajustar en caso de que la cantidad asignada no coincida exactamente con n_sin_asignar
    if len(asignaciones) > n_sin_asignar:
        asignaciones = asignaciones[:n_sin_asignar]  # Cortar exceso
    elif len(asignaciones) < n_sin_asignar:
        estrato_max = porcentajes_obj.idxmax()
        asignaciones.extend([estrato_max] * (n_sin_asignar - len(asignaciones)))  # Completar con el estrato mayoritario

    # Mezclar aleatoriamente las asignaciones para evitar sesgo en el orden
    np.random.shuffle(asignaciones)

    # Asignar los estratos calculados a las filas que no tenían estrato asignado
    grupo.loc[grupo['fami_estratovivienda'].isna(), 'fami_estratovivienda'] = asignaciones

    # Validar el error entre la distribución final y la distribución objetivo
    conteo_final = grupo['fami_estratovivienda'].value_counts(normalize=True) * 100
    error = (conteo_final.reindex(porcentajes_obj.index, fill_value=0) - porcentajes_obj).abs()

    if error.max() > 5:
        # Si el error máximo es mayor a 5%, reasignar todo al segundo estrato mayoritario
        segundo_estrato = porcentajes_obj.sort_values(ascending=False).index[1]
        grupo['fami_estratovivienda'] = segundo_estrato

        print(f"Advertencia: Error > 5% para combinación {combo}. Se reasignó todo a {segundo_estrato}.")

    # Retornar el grupo con las asignaciones realizadas
    return grupo

In [373]:
# Filtrar solo las filas donde la columna 'cole_naturaleza' sea 'OFICIAL'
df_oficial = df_final1[df_final1['cole_naturaleza'] == 'OFICIAL'].copy()

# Agrupar el DataFrame filtrado por las combinaciones de las columnas indicadas,
# luego aplicar la función 'asignar_estrato' a cada grupo para asignar estratos faltantes
datos_oficiales_estrato = df_oficial.groupby(
    ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']
).apply(asignar_estrato_oficial)

# Reiniciar el índice del DataFrame resultante para evitar índices multi-nivel
datos_oficiales_estrato.reset_index(drop=True, inplace=True)

C:\Users\evivas\AppData\Local\Temp\ipykernel_5892\335551381.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ).apply(asignar_estrato_oficial)

In [374]:
datos_oficiales_estrato

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20172,TI,N,A,NaN,ANTIOQUIA,MIXTO,TARDE,OFICIAL,M,...,No,No,No,A-,43.0,51.0,40,54,49,240
1,20172,TI,N,A,ACADÉMICO,LA GUAJIRA,MIXTO,MAÑANA,OFICIAL,F,...,No,No,No,A-,35.0,38.0,35,36,35,180
2,20172,CC,N,A,TÉCNICO/ACADÉMICO,LA GUAJIRA,MIXTO,UNICA,OFICIAL,F,...,No,No,No,A-,37.0,47.0,45,52,53,242
3,20172,TI,S,A,TÉCNICO/ACADÉMICO,CAUCA,MIXTO,MAÑANA,OFICIAL,F,...,No,No,No,A-,44.0,47.0,40,43,51,226
4,20172,TI,N,A,ACADÉMICO,SUCRE,MIXTO,MAÑANA,OFICIAL,F,...,No,No,No,A-,35.0,38.0,47,46,42,213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381373,20172,TI,N,A,ACADÉMICO,SANTANDER,MIXTO,MAÑANA,OFICIAL,M,...,Si,Si,Si,A1,55.0,56.0,43,51,47,248
381374,20172,CC,N,A,TÉCNICO/ACADÉMICO,VALLE,MIXTO,NOCHE,OFICIAL,F,...,Si,Si,Si,A-,42.0,36.0,38,39,44,197
381375,20172,CC,N,A,TÉCNICO/ACADÉMICO,VALLE,MIXTO,NOCHE,OFICIAL,F,...,Si,Si,Si,A-,42.0,36.0,38,39,44,197
381376,20172,TI,N,A,TÉCNICO,ATLANTICO,MIXTO,MAÑANA,OFICIAL,M,...,Si,Si,Si,A2,58.0,53.0,65,60,64,302
381377,20172,TI,N,A,ACADÉMICO,CUNDINAMARCA,MIXTO,UNICA,OFICIAL,F,...,Si,Si,Si,A1,54.0,53.0,54,59,64,286

In [375]:
# Aplicar la función 'parse_estratos' para convertir la columna 'frecuencia_estratos' de strings a diccionarios
df_resultado_nooficial['estratos_dict'] = df_resultado_nooficial['frecuencia_estratos'].apply(parse_estratos)

# Aplicar la función 'dict_to_pct' para calcular el porcentaje que representa cada estrato respecto al total,
# luego expandir estos porcentajes a columnas separadas, y llenar valores NaN con 0
df_pct = df_resultado_nooficial['estratos_dict'].apply(dict_to_pct).apply(pd.Series).fillna(0)

# Unir el DataFrame original (sin las columnas originales de strings y diccionarios) con el DataFrame de porcentajes
df_resultado_nooficial_estratos = pd.concat([df_resultado_nooficial.drop(columns=['frecuencia_estratos', 'estratos_dict']), df_pct], axis=1)

# Mostrar el DataFrame final resultante con los porcentajes por estrato para cada fila
print(df_resultado_nooficial_estratos)

   fami_tienecomputador fami_tieneinternet fami_tieneautomovil  \
0                    Si                 Si                  Si
1                    Si                 Si                  No
2                    No                 No                  No
3                    No                 No                  No
4                    No                 Si                  No
5                    Si                 Si                  No
6                    Si                 No                  No
7                    No                 Si                  No
8                    No                 Si                  Si
9                    Si                 No                  Si
10                   Si                 No                  No
11                   Si                 Si                  Si
12                   No                 No                  Si
13                   No                 No                  Si
14                   Si                 No                  Si
15                   No                 Si                  Si

   fami_tienelavadora  porcentaje  \
0                  Si       41.59
1                  Si       28.07
2                  Si        6.37
3                  No        4.83
4                  Si        4.45
5                  No        3.35
6                  Si        3.32
7                  No        1.53
8                  Si        1.39
9                  Si        1.33
10                 No        1.22
11                 No        0.97
12                 Si        0.89
13                 No        0.31
14                 No        0.19
15                 No        0.18

                         frecuencia_desemp_ingles  Estrato 3  Estrato 4  \
0   B1:13151, A2:12224, A1:9946, B+:8480, A-:7385  37.667695  23.048064
1    A-:10673, A1:9624, A2:7843, B1:4990, B+:1416  38.964443   7.632721
2         A-:5058, A1:1835, A2:652, B1:252, B+:47  11.738236   1.555670
3         A-:4166, A1:1182, A2:399, B1:167, B+:28   6.665533   1.224282
4         A-:2718, A1:1503, A2:800, B1:378, B+:73  26.709797   4.103512
5         A-:1701, A1:1162, A2:779, B1:403, B+:82  24.602981   3.615930
6         A-:2148, A1:1061, A2:576, B1:254, B+:53  21.296067   3.240168
7          A-:1050, A1:442, A2:265, B1:116, B+:16  20.719270   4.240472
8           A-:602, A1:468, A2:370, B1:227, B+:46  38.574794  11.366313
9           A-:652, A1:450, A2:284, B1:195, B+:60  31.958128   9.051724
10           A-:832, A1:413, A2:162, B1:74, B+:20  12.172159   2.555481
11          A-:386, A1:280, A2:254, B1:204, B+:72  35.979730  13.597973
12           A-:625, A1:274, A2:144, B1:42, B+:16  21.009174   3.119266
13              A-:287, A1:56, A2:22, B1:14, B+:4  10.344828   1.591512
14              A-:143, A1:48, A2:18, B1:16, B+:3  18.303571   4.910714
15              A-:109, A1:60, A2:30, B1:20, B+:6  24.774775   4.054054

    Estrato 2  Estrato 5  Estrato 6  Estrato 1  Sin Estrato
0   17.243818  11.518139   7.509183   2.590796     0.422306
1   39.835173   1.604590   0.439733  10.961298     0.562043
2   39.521728   0.578555   0.462844  42.915917     3.227051
3   32.001360   0.510117   0.391090  54.769597     4.438021
4   44.750462   1.164510   0.665434  20.850277     1.756007
5   46.274127   0.659663   0.464207  23.210359     1.172734
6   41.998516   1.038833   0.494682  29.755132     2.176602
7   42.673108   1.502952   1.449275  26.516371     2.898551
8   34.452297   4.181390   1.177856   8.657244     1.590106
9   35.714286   3.386700   1.046798  16.071429     2.770936
10  43.510424   0.739744   0.672495  37.390720     2.958978
11  34.037162   4.054054   1.435811   9.459459     1.435811
12  43.486239   1.192661   0.550459  27.889908     2.752294
13  35.278515   1.061008   0.265252  46.419098     5.039788
14  41.071429   4.464286   2.678571  25.892857     2.678571
15  43.693694   5.405405   1.801802  17.567568     2.702703

In [376]:
def asignar_estrato_nooficial(grupo):
    # Obtener la combinación actual de variables del grupo (nombre del grupo)
    combo = grupo.name  
    # Contar el total de filas en este grupo
    total = len(grupo)
    
    # Buscar en el DataFrame de porcentajes el registro que corresponde a esta combinación
    filtro = (
        (df_resultado_nooficial_estratos['fami_tienecomputador'] == combo[0]) &
        (df_resultado_nooficial_estratos['fami_tieneinternet'] == combo[1]) &
        (df_resultado_nooficial_estratos['fami_tieneautomovil'] == combo[2]) &
        (df_resultado_nooficial_estratos['fami_tienelavadora'] == combo[3])
    )
    
    # Extraer la fila con los porcentajes para la combinación actual
    fila_estratos = df_resultado_nooficial_estratos.loc[filtro]
    # Si no hay datos para esta combinación, devolver el grupo sin cambios
    if fila_estratos.empty:
        return grupo  

    # Tomar los porcentajes de participación de cada estrato (columnas que contienen 'Estrato')
    porcentajes_obj = fila_estratos.iloc[0].filter(like='Estrato').astype(float)
    estratos_disponibles = porcentajes_obj.index.tolist()

    # Dividir filas del grupo en asignados (con estrato) y sin asignar (sin estrato)
    asignados = grupo[grupo['fami_estratovivienda'].notna()]
    sin_asignar = grupo[grupo['fami_estratovivienda'].isna()]
    n_sin_asignar = len(sin_asignar)

    # Contar cuántos estratos ya están asignados en el grupo
    conteo_actual = asignados['fami_estratovivienda'].value_counts()
    # Calcular el porcentaje actual que representan en el grupo
    porcentaje_actual = (conteo_actual / total) * 100
    # Calcular cuánto porcentaje falta asignar para cumplir con los porcentajes objetivo
    porcentaje_faltante = porcentajes_obj - porcentaje_actual.reindex(porcentajes_obj.index, fill_value=0)
    # Evitar valores negativos (no asignar menos de 0)
    porcentaje_faltante = porcentaje_faltante.clip(lower=0)

    # Convertir el porcentaje faltante en cantidad entera de filas por asignar
    filas_por_asignar = (porcentaje_faltante * total / 100).round().astype(int)
    # Calcular diferencia por posibles redondeos
    diferencia = n_sin_asignar - filas_por_asignar.sum()

    # Ajustar la diferencia sumándola al estrato con mayor asignación prevista
    if diferencia != 0:
        estrato_ajuste = filas_por_asignar.idxmax()
        filas_por_asignar[estrato_ajuste] += diferencia

    # Crear lista con asignaciones repetidas según cantidad calculada
    asignaciones = []
    for estrato, cantidad in filas_por_asignar.items():
        asignaciones.extend([estrato] * cantidad)

    # Ajustar la lista por si hay discrepancia con la cantidad de filas sin asignar
    if len(asignaciones) > n_sin_asignar:
        asignaciones = asignaciones[:n_sin_asignar]  # cortar exceso
    elif len(asignaciones) < n_sin_asignar:
        estrato_max = porcentajes_obj.idxmax()
        asignaciones.extend([estrato_max] * (n_sin_asignar - len(asignaciones)))  # rellenar faltante

    # Mezclar aleatoriamente las asignaciones para evitar sesgos
    np.random.shuffle(asignaciones)
    # Asignar los estratos calculados a las filas sin estrato
    grupo.loc[grupo['fami_estratovivienda'].isna(), 'fami_estratovivienda'] = asignaciones

    # Validar que el error absoluto en porcentaje no supere el 5%
    conteo_final = grupo['fami_estratovivienda'].value_counts(normalize=True) * 100
    error = (conteo_final.reindex(porcentajes_obj.index, fill_value=0) - porcentajes_obj).abs()

    # Si el error máximo supera el 5%, reasignar todo al segundo estrato más grande para evitar inconsistencias
    if error.max() > 5:
        segundo_estrato = porcentajes_obj.sort_values(ascending=False).index[1]
        grupo['fami_estratovivienda'] = segundo_estrato

        print(f"Advertencia: Error > 5% para combinación {combo}. Se reasignó todo a {segundo_estrato}.")

    # Devolver el grupo con estratos asignados y corregidos
    return grupo

In [377]:
# Filtrar solo las filas no oficiales
df_nooficial = df_final1[df_final1['cole_naturaleza'] == 'NO OFICIAL'].copy()

# Agrupar el DataFrame filtrado por las combinaciones de las columnas indicadas,
# luego aplicar la función 'asignar_estrato_nooficial' a cada grupo para asignar estratos faltantes
datos_nooficial_estrato = df_nooficial.groupby(
    ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tieneautomovil', 'fami_tienelavadora']
).apply(asignar_estrato_nooficial)

# Limpiar índice
datos_nooficial_estrato.reset_index(drop=True, inplace=True)

C:\Users\evivas\AppData\Local\Temp\ipykernel_5892\3230652546.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ).apply(asignar_estrato_nooficial)

In [378]:
datos_nooficial_estrato

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20172,CC,N,A,ACADÉMICO,BOGOTA,MIXTO,NOCHE,NO OFICIAL,F,...,No,No,No,A-,32.0,44.0,42,51,48,226
1,20172,CC,N,A,ACADÉMICO,SANTANDER,MIXTO,COMPLETA,NO OFICIAL,F,...,No,No,No,A-,42.0,33.0,46,42,42,204
2,20172,CC,N,A,TÉCNICO/ACADÉMICO,BOGOTA,MIXTO,MAÑANA,NO OFICIAL,F,...,No,No,No,A-,39.0,32.0,30,36,37,171
3,20172,TI,N,A,ACADÉMICO,BOLIVAR,MIXTO,MAÑANA,NO OFICIAL,M,...,No,No,No,A-,39.0,49.0,46,52,45,237
4,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,NOCHE,NO OFICIAL,F,...,No,No,No,A-,36.0,30.0,29,31,43,167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131011,20171,TI,S,B,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,M,...,Si,Si,Si,B+,85.0,58.0,71,60,63,323
131012,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,M,...,Si,Si,Si,A-,44.0,45.0,49,46,53,240
131013,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A2,65.0,50.0,50,46,54,256
131014,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A1,55.0,49.0,51,52,55,260
131015,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,Si,A1,48.0,40.0,50,54,62,256

In [379]:
def calcular_participacion_por_combinacion(df):

    # Definir las columnas que se usarán para formar las combinaciones
    cols = ['fami_tienecomputador', 'fami_tieneinternet', 'fami_tienelavadora', 'fami_tieneautomovil']

    # Crear una nueva columna llamada 'combinacion' que agrupa los valores de las columnas definidas en una tupla por fila
    df['combinacion'] = df[cols].apply(lambda row: tuple(row.values), axis=1)

    # Agrupar el DataFrame por 'combinacion' y 'fami_estratovivienda' para contar cuántas filas hay en cada grupo
    conteo = df.groupby(['combinacion', 'fami_estratovivienda']).size().reset_index(name='cuenta')

    # Calcular el total de filas por cada combinación para poder calcular porcentajes dentro de cada grupo de combinación
    total_por_comb = conteo.groupby('combinacion')['cuenta'].transform('sum')

    # Calcular el porcentaje que representa cada estrato dentro de su combinación correspondiente
    conteo['porcentaje_participacion'] = (conteo['cuenta'] / total_por_comb) * 100

    # Devolver el DataFrame con la combinación, estrato, cuenta y porcentaje de participación
    return conteo

In [382]:
# Evaluar el porcentaje de participación de cada estrato en cada combinacion para los datos con colegios no oficiales
evaluacion1 = calcular_participacion_por_combinacion(datos_nooficial_estrato)
print(evaluacion1)

          combinacion fami_estratovivienda  cuenta  porcentaje_participacion
0    (No, No, No, No)            Estrato 1    3510                 54.783830
1    (No, No, No, No)            Estrato 2    2050                 31.996254
2    (No, No, No, No)            Estrato 3     427                  6.664586
3    (No, No, No, No)            Estrato 4      78                  1.217418
4    (No, No, No, No)            Estrato 5      33                  0.515062
..                ...                  ...     ...                       ...
107  (Si, Si, Si, Si)            Estrato 3   19630                 37.645028
108  (Si, Si, Si, Si)            Estrato 4   12018                 23.047272
109  (Si, Si, Si, Si)            Estrato 5    6006                 11.517883
110  (Si, Si, Si, Si)            Estrato 6    3916                  7.509828
111  (Si, Si, Si, Si)          Sin Estrato     224                  0.429571

[112 rows x 4 columns]

In [383]:
# Evaluar el porcentaje de participación de cada estrato en cada combinacion para los datos con colegios no oficiales
evaluacion2 = calcular_participacion_por_combinacion(datos_oficiales_estrato)
print(evaluacion2)

          combinacion fami_estratovivienda  cuenta  porcentaje_participacion
0    (No, No, No, No)            Estrato 1   39899                 64.002246
1    (No, No, No, No)            Estrato 2   14202                 22.781521
2    (No, No, No, No)            Estrato 3    2718                  4.359962
3    (No, No, No, No)            Estrato 4     719                  1.153353
4    (No, No, No, No)            Estrato 5     328                  0.526147
..                ...                  ...     ...                       ...
107  (Si, Si, Si, Si)            Estrato 3   12767                 35.741881
108  (Si, Si, Si, Si)            Estrato 4    2227                  6.234602
109  (Si, Si, Si, Si)            Estrato 5     440                  1.231803
110  (Si, Si, Si, Si)            Estrato 6     163                  0.456327
111  (Si, Si, Si, Si)          Sin Estrato     256                  0.716685

[112 rows x 4 columns]

In [384]:
df_final2 = pd.concat([datos_oficiales_estrato, datos_nooficial_estrato], axis=0, ignore_index=True)
print(df_final2)

        periodo estu_tipodocumento cole_bilingue cole_calendario  \
0         20172                 TI             N               A
1         20172                 TI             N               A
2         20172                 CC             N               A
3         20172                 TI             S               A
4         20172                 TI             N               A
...         ...                ...           ...             ...
512389    20171                 TI             S               B
512390    20172                 TI             N               A
512391    20172                 TI             N               A
512392    20172                 TI             N               A
512393    20172                 TI             N               A

            cole_caracter cole_depto_ubicacion cole_genero cole_jornada  \
0                     NaN            ANTIOQUIA       MIXTO        TARDE
1               ACADÉMICO           LA GUAJIRA       MIXTO       MAÑANA
2       TÉCNICO/ACADÉMICO           LA GUAJIRA       MIXTO        UNICA
3       TÉCNICO/ACADÉMICO                CAUCA       MIXTO       MAÑANA
4               ACADÉMICO                SUCRE       MIXTO       MAÑANA
...                   ...                  ...         ...          ...
512389          ACADÉMICO               BOGOTA       MIXTO     COMPLETA
512390          ACADÉMICO               BOGOTA       MIXTO     COMPLETA
512391          ACADÉMICO               BOGOTA       MIXTO     COMPLETA
512392          ACADÉMICO               BOGOTA       MIXTO     COMPLETA
512393          ACADÉMICO            ANTIOQUIA       MIXTO     COMPLETA

       cole_naturaleza estu_genero  ... fami_tieneinternet fami_tienelavadora  \
0              OFICIAL           M  ...                 No                 No
1              OFICIAL           F  ...                 No                 No
2              OFICIAL           F  ...                 No                 No
3              OFICIAL           F  ...                 No                 No
4              OFICIAL           F  ...                 No                 No
...                ...         ...  ...                ...                ...
512389      NO OFICIAL           M  ...                 Si                 Si
512390      NO OFICIAL           M  ...                 Si                 Si
512391      NO OFICIAL           F  ...                 Si                 Si
512392      NO OFICIAL           F  ...                 Si                 Si
512393      NO OFICIAL           F  ...                 Si                 Si

       desemp_ingles punt_ingles punt_matematicas punt_sociales_ciudadanas  \
0                 A-        43.0             51.0                       40
1                 A-        35.0             38.0                       35
2                 A-        37.0             47.0                       45
3                 A-        44.0             47.0                       40
4                 A-        35.0             38.0                       47
...              ...         ...              ...                      ...
512389            B+        85.0             58.0                       71
512390            A-        44.0             45.0                       49
512391            A2        65.0             50.0                       50
512392            A1        55.0             49.0                       51
512393            A1        48.0             40.0                       50

       punt_c_naturales punt_lectura_critica punt_global       combinacion
0                    54                   49         240  (No, No, No, No)
1                    36                   35         180  (No, No, No, No)
2                    52                   53         242  (No, No, No, No)
3                    43                   51         226  (No, No, No, No)
4                    46                   42         213  (No, No, No, No)
...                 ...                  ...         ...               ...
512389               60                   63         323  (Si, Si, Si, Si)
512390               46                   53         240  (Si, Si, Si, Si)
512391               46                   54         256  (Si, Si, Si, Si)
512392               52                   55         260  (Si, Si, Si, Si)
512393               54                   62         256  (Si, Si, Si, Si)

[512394 rows x 30 columns]

In [385]:
# Contar la cantidad de datos faltantes en cada columna
numero_datos_faltantes = df_final2.isna().sum()
# Mostrar el resultado
print(numero_datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue                   0
cole_calendario                 0
cole_caracter                7573
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     0
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8344
fami_educacionmadre         24162
fami_educacionpadre         24204
fami_estratovivienda            0
fami_personashogar          10901
fami_tieneautomovil             0
fami_tienecomputador            0
fami_tieneinternet              0
fami_tienelavadora              0
desemp_ingles                   0
punt_ingles                     0
punt_matematicas                0
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
combinacion                     0
dtype: int64

In [386]:
# Crear una tabla de frecuencias cruzadas entre estrato de vivienda y educación de la madre
tabla_frecuencias_estrato_educacion_mama = pd.crosstab(df['fami_estratovivienda'], df['fami_educacionmadre'])

# Calcular la suma total de cada fila (total de casos por cada estrato)
suma_por_fila = tabla_frecuencias_estrato_educacion_mama.sum(axis=1)

# Dividir cada valor de la tabla de frecuencias por el total de su fila para obtener proporciones,
# y luego multiplicar por 100 para convertirlas en porcentajes
tabla_porcentajes_estrato_educacion_mama = tabla_frecuencias_estrato_educacion_mama.div(suma_por_fila, axis=0) * 100

# Mostrar la tabla resultante con porcentajes por estrato y nivel educativo de la madre
print(tabla_porcentajes_estrato_educacion_mama)

fami_educacionmadre   Educación profesional completa  \
fami_estratovivienda
Estrato 1                                   3.892438
Estrato 2                                   8.365294
Estrato 3                                  17.860346
Estrato 4                                  32.229076
Estrato 5                                  34.509327
Estrato 6                                  34.911049
Sin Estrato                                 4.355043

fami_educacionmadre   Educación profesional incompleta   Ninguno  Postgrado  \
fami_estratovivienda
Estrato 1                                     1.085153  4.242188   0.344179
Estrato 2                                     2.172165  1.741781   1.081744
Estrato 3                                     4.402198  1.115498   3.894966
Estrato 4                                     5.751399  1.401087  11.739717
Estrato 5                                     5.383212  1.824818  16.859286
Estrato 6                                     4.716827  1.632120  20.825853
Sin Estrato                                   1.501739  8.401834   0.798293

fami_educacionmadre   Primaria completa  Primaria incompleta  \
fami_estratovivienda
Estrato 1                     15.705938            26.402714
Estrato 2                     11.648127            14.671804
Estrato 3                      6.259987             7.769312
Estrato 4                      5.963809             5.849434
Estrato 5                      7.035685             5.504866
Estrato 6                      6.903868             5.124857
Sin Estrato                   15.799874            27.869112

fami_educacionmadre   Secundaria (Bachillerato) completa  \
fami_estratovivienda
Estrato 1                                      22.314044
Estrato 2                                      28.844964
Estrato 3                                      27.340021
Estrato 4                                      16.392304
Estrato 5                                      11.303731
Estrato 6                                      10.918884
Sin Estrato                                    18.439772

fami_educacionmadre   Secundaria (Bachillerato) incompleta  \
fami_estratovivienda
Estrato 1                                        17.387213
Estrato 2                                        17.270303
Estrato 3                                        13.195253
Estrato 4                                         6.466239
Estrato 5                                         7.096513
Estrato 6                                         7.915783
Sin Estrato                                      16.250395

fami_educacionmadre   Técnica o tecnológica completa  \
fami_estratovivienda
Estrato 1                                   6.554251
Estrato 2                                  10.797772
Estrato 3                                  13.927235
Estrato 4                                  10.510192
Estrato 5                                   7.806164
Estrato 6                                   5.157500
Sin Estrato                                 3.817578

fami_educacionmadre   Técnica o tecnológica incompleta
fami_estratovivienda
Estrato 1                                     2.071881
Estrato 2                                     3.406047
Estrato 3                                     4.235183
Estrato 4                                     3.696744
Estrato 5                                     2.676399
Estrato 6                                     1.893259
Sin Estrato                                   2.766361

In [387]:
# Crear una tabla de frecuencias cruzadas entre estrato de vivienda y educación del padre
tabla_frecuencias_estrato_educacion_padre = pd.crosstab(df['fami_estratovivienda'], df['fami_educacionpadre'])

# Calcular la suma total de cada fila (total de casos por cada estrato)
suma_por_fila = tabla_frecuencias_estrato_educacion_padre.sum(axis=1)

# Dividir cada valor de la tabla de frecuencias por el total de su fila para obtener proporciones,
# y luego multiplicar por 100 para convertirlas en porcentajes
tabla_porcentajes_estrato_educacion_padre = tabla_frecuencias_estrato_educacion_padre.div(suma_por_fila, axis=0) * 100

# Mostrar la tabla resultante con los porcentajes por estrato y nivel educativo del padre
print(tabla_porcentajes_estrato_educacion_padre)

fami_educacionpadre   Educación profesional completa  \
fami_estratovivienda
Estrato 1                                   3.833802
Estrato 2                                   7.642047
Estrato 3                                  16.890678
Estrato 4                                  31.119010
Estrato 5                                  31.512945
Estrato 6                                  29.565076
Sin Estrato                                 4.429530

fami_educacionpadre   Educación profesional incompleta    Ninguno  Postgrado  \
fami_estratovivienda
Estrato 1                                     0.982629   6.148715   0.306258
Estrato 2                                     1.879087   3.030057   0.916374
Estrato 3                                     3.901105   2.195726   3.467534
Estrato 4                                     4.608408   3.370511  11.917310
Estrato 5                                     4.045307   4.530744  18.497168
Estrato 6                                     4.023457   5.033393  24.906337
Sin Estrato                                   1.666009  11.717331   0.773786

fami_educacionpadre   Primaria completa  Primaria incompleta  \
fami_estratovivienda
Estrato 1                     14.988655            32.889859
Estrato 2                     12.474151            20.240157
Estrato 3                      7.404769            10.617322
Estrato 4                      5.535809             6.843159
Estrato 5                      4.510518             6.512945
Estrato 6                      3.779117             6.271380
Sin Estrato                   13.967627            31.867351

fami_educacionpadre   Secundaria (Bachillerato) completa  \
fami_estratovivienda
Estrato 1                                      19.319041
Estrato 2                                      26.260303
Estrato 3                                      26.879323
Estrato 4                                      17.334641
Estrato 5                                      13.359628
Estrato 6                                      13.422381
Sin Estrato                                    15.981050

fami_educacionpadre   Secundaria (Bachillerato) incompleta  \
fami_estratovivienda
Estrato 1                                        15.775378
Estrato 2                                        17.275555
Estrato 3                                        14.700114
Estrato 4                                         8.894064
Estrato 5                                         8.464806
Estrato 6                                         6.434273
Sin Estrato                                      13.864982

fami_educacionpadre   Técnica o tecnológica completa  \
fami_estratovivienda
Estrato 1                                   4.378123
Estrato 2                                   7.912556
Estrato 3                                  10.750490
Estrato 4                                   7.929893
Estrato 5                                   5.390372
Estrato 6                                   4.056035
Sin Estrato                                 3.363600

fami_educacionpadre   Técnica o tecnológica incompleta
fami_estratovivienda
Estrato 1                                     1.377540
Estrato 2                                     2.369712
Estrato 3                                     3.192939
Estrato 4                                     2.447195
Estrato 5                                     3.175566
Estrato 6                                     2.508552
Sin Estrato                                   2.368733

In [388]:
def imputar_educacion_madre(df, tabla_porcentajes):
    # Crear una copia del dataframe para no modificar el original
    df_copy = df.copy()

    # Iterar sobre cada estrato en la tabla de porcentajes objetivo
    for estrato in tabla_porcentajes.index:
        # Crear una máscara para filtrar las filas que pertenecen a este estrato
        mask_estrato = df_copy['fami_estratovivienda'] == estrato
        sub_df = df_copy.loc[mask_estrato]

        # Si no hay valores nulos en 'fami_educacionmadre' para este estrato, continuar con el siguiente estrato
        if sub_df['fami_educacionmadre'].isna().sum() == 0:
            continue

        # Obtener la distribución objetivo de educación de madre para este estrato desde la tabla de porcentajes
        dist_objetivo = tabla_porcentajes.loc[estrato]

        # Contar la cantidad actual de cada nivel de educación en el subconjunto (excluyendo valores nulos)
        conteo_actual = sub_df['fami_educacionmadre'].value_counts()
        total_actual = conteo_actual.sum()  # Total de registros no nulos en este estrato

        # Asegurar que el conteo actual incluya todos los niveles de educación (llenar con 0 si falta alguno)
        conteo_actual = conteo_actual.reindex(dist_objetivo.index, fill_value=0)

        # Obtener los índices de las filas donde la educación de la madre está nula para este estrato
        indices_nulos = df_copy.loc[mask_estrato & df_copy['fami_educacionmadre'].isna()].index

        # Iterar sobre cada índice de fila con valor nulo para imputar
        for idx in indices_nulos:
            # Ordenar los niveles de educación por su porcentaje objetivo, de mayor a menor
            candidatos = dist_objetivo.sort_values(ascending=False).index.tolist()

            asignado = None  # Variable para guardar la educación que se asignará

            # Probar asignar cada nivel de educación en orden para minimizar desviación
            for educ in candidatos:
                # Simular la asignación sumando uno al conteo actual para ese nivel de educación
                conteo_sim = conteo_actual.copy()
                conteo_sim[educ] += 1
                total_sim = total_actual + 1  # Nuevo total después de la asignación
                porcentaje_sim = (conteo_sim / total_sim) * 100  # Calcular el nuevo porcentaje simulado

                # Calcular la diferencia absoluta entre la simulación y la distribución objetivo
                diferencia = (porcentaje_sim - dist_objetivo).abs()

                # Si la diferencia máxima es menor o igual a 5%, se acepta la asignación
                if diferencia.max() <= 5:
                    asignado = educ
                    break  # Salir del ciclo, asignación aceptable encontrada

            # Si ningún candidato cumple la condición de error <= 5%
            if asignado is None:
                # Si hay más de un candidato, asignar el segundo mejor porcentaje
                if len(candidatos) > 1:
                    asignado = candidatos[1]
                else:
                    # Si solo hay un candidato, asignar ese
                    asignado = candidatos[0]

            # Asignar el valor imputado al dataframe
            df_copy.at[idx, 'fami_educacionmadre'] = asignado

            # Actualizar conteo real para futuras asignaciones
            conteo_actual[asignado] += 1
            total_actual += 1

    # Devolver el dataframe con las imputaciones realizadas
    return df_copy

In [389]:
# Llamar a la función 'imputar_educacion_madre' para imputar valores faltantes en 'fami_educacionmadre'
# Se pasa el dataframe 'df_final2' y la tabla de porcentajes por estrato 'tabla_porcentajes_estrato_educacion_mama'
df_final3 = imputar_educacion_madre(df_final2, tabla_porcentajes_estrato_educacion_mama)

# Mostrar el dataframe resultante después de la imputación
df_final3

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global,combinacion
0,20172,TI,N,A,NaN,ANTIOQUIA,MIXTO,TARDE,OFICIAL,M,...,No,No,A-,43.0,51.0,40,54,49,240,"(No, No, No, No)"
1,20172,TI,N,A,ACADÉMICO,LA GUAJIRA,MIXTO,MAÑANA,OFICIAL,F,...,No,No,A-,35.0,38.0,35,36,35,180,"(No, No, No, No)"
2,20172,CC,N,A,TÉCNICO/ACADÉMICO,LA GUAJIRA,MIXTO,UNICA,OFICIAL,F,...,No,No,A-,37.0,47.0,45,52,53,242,"(No, No, No, No)"
3,20172,TI,S,A,TÉCNICO/ACADÉMICO,CAUCA,MIXTO,MAÑANA,OFICIAL,F,...,No,No,A-,44.0,47.0,40,43,51,226,"(No, No, No, No)"
4,20172,TI,N,A,ACADÉMICO,SUCRE,MIXTO,MAÑANA,OFICIAL,F,...,No,No,A-,35.0,38.0,47,46,42,213,"(No, No, No, No)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512389,20171,TI,S,B,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,M,...,Si,Si,B+,85.0,58.0,71,60,63,323,"(Si, Si, Si, Si)"
512390,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,M,...,Si,Si,A-,44.0,45.0,49,46,53,240,"(Si, Si, Si, Si)"
512391,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A2,65.0,50.0,50,46,54,256,"(Si, Si, Si, Si)"
512392,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,55.0,49.0,51,52,55,260,"(Si, Si, Si, Si)"
512393,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,48.0,40.0,50,54,62,256,"(Si, Si, Si, Si)"

In [392]:
# Crear tabla de contingencia entre 'fami_estratovivienda' y 'fami_educacionmadre' para evaluar distribución tras imputación
evaluacion3 = pd.crosstab(df_final3['fami_estratovivienda'], df_final3['fami_educacionmadre'])

# Calcular el total de casos por cada estrato (suma de cada fila)
suma_por_fila = evaluacion3.sum(axis=1)

# Convertir los conteos a porcentajes por fila (estrato), dividiendo cada valor por el total de su fila y multiplicando por 100
evaluacion3 = evaluacion3.div(suma_por_fila, axis=0) * 100

# Mostrar la tabla de porcentajes resultante para verificar la distribución por estrato y educación de la madre
print(evaluacion3)

fami_educacionmadre   Educación profesional completa  \
fami_estratovivienda
Estrato 1                                   3.715067
Estrato 2                                   7.940090
Estrato 3                                  17.104837
Estrato 4                                  34.064327
Estrato 5                                  36.309232
Estrato 6                                  36.576862
Sin Estrato                                 4.182967

fami_educacionmadre   Educación profesional incompleta   Ninguno  Postgrado  \
fami_estratovivienda
Estrato 1                                     1.038282  4.044634   0.330150
Estrato 2                                     2.064967  1.666331   1.028949
Estrato 3                                     4.210753  1.089461   3.719466
Estrato 4                                     5.587166  1.359254  11.387703
Estrato 5                                     5.238889  1.765918  16.344550
Estrato 6                                     4.595880  1.584786  20.253566
Sin Estrato                                   1.436955  8.012338   0.759856

fami_educacionmadre   Primaria completa  Primaria incompleta  \
fami_estratovivienda
Estrato 1                     14.909267            30.044856
Estrato 2                     11.048146            13.913105
Estrato 3                      6.028810             7.477176
Estrato 4                      5.792635             5.689900
Estrato 5                      6.828215             5.356617
Estrato 6                      6.719493             4.992076
Sin Estrato                   15.182064            30.928378

fami_educacionmadre   Secundaria (Bachillerato) completa  \
fami_estratovivienda
Estrato 1                                      21.207791
Estrato 2                                      32.551108
Estrato 3                                      30.380380
Estrato 4                                      15.975186
Estrato 5                                      11.086039
Estrato 6                                      10.681458
Sin Estrato                                    17.657237

fami_educacionmadre   Secundaria (Bachillerato) incompleta  \
fami_estratovivienda
Estrato 1                                        16.509855
Estrato 2                                        16.341359
Estrato 3                                        12.636183
Estrato 4                                         6.302355
Estrato 5                                         6.887079
Estrato 6                                         7.717908
Sin Estrato                                      15.543184

fami_educacionmadre   Técnica o tecnológica completa  \
fami_estratovivienda
Estrato 1                                   6.220944
Estrato 2                                  10.214437
Estrato 3                                  13.299077
Estrato 4                                  10.241821
Estrato 5                                   7.593446
Estrato 6                                   5.039620
Sin Estrato                                 3.663858

fami_educacionmadre   Técnica o tecnológica incompleta
fami_estratovivienda
Estrato 1                                     1.979153
Estrato 2                                     3.231508
Estrato 3                                     4.053855
Estrato 4                                     3.599652
Estrato 5                                     2.590013
Estrato 6                                     1.838352
Sin Estrato                                   2.633163

In [393]:
# Contar la cantidad de datos faltantes en cada columna
numero_datos_faltantes = df_final3.isna().sum()

# Mostrar el resultado
print(numero_datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue                   0
cole_calendario                 0
cole_caracter                7573
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     0
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8344
fami_educacionmadre             0
fami_educacionpadre         24204
fami_estratovivienda            0
fami_personashogar          10901
fami_tieneautomovil             0
fami_tienecomputador            0
fami_tieneinternet              0
fami_tienelavadora              0
desemp_ingles                   0
punt_ingles                     0
punt_matematicas                0
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
combinacion                     0
dtype: int64

In [394]:
def imputar_educacion_padre(df, tabla_porcentajes):
    # Crear una copia del dataframe para no modificar el original directamente
    df_copy = df.copy()

    # Iterar sobre cada estrato en la tabla de porcentajes objetivo
    for estrato in tabla_porcentajes.index:
        # Filtrar las filas del dataframe que corresponden al estrato actual
        mask_estrato = df_copy['fami_estratovivienda'] == estrato
        sub_df = df_copy.loc[mask_estrato]

        # Si en este estrato no hay valores nulos en 'fami_educacionpadre', pasar al siguiente estrato
        if sub_df['fami_educacionpadre'].isna().sum() == 0:
            continue

        # Obtener la distribución porcentual objetivo para este estrato desde la tabla de porcentajes
        dist_objetivo = tabla_porcentajes.loc[estrato]

        # Contar la cantidad actual de cada nivel de educación del padre en el subgrupo sin valores nulos
        conteo_actual = sub_df['fami_educacionpadre'].value_counts()
        total_actual = conteo_actual.sum()

        # Asegurar que todos los niveles de educación estén presentes en el conteo, rellenando con 0 donde falten
        conteo_actual = conteo_actual.reindex(dist_objetivo.index, fill_value=0)

        # Obtener los índices de las filas que necesitan imputación (valores nulos en 'fami_educacionpadre' dentro del estrato)
        indices_nulos = df_copy.loc[mask_estrato & df_copy['fami_educacionpadre'].isna()].index

        # Iterar sobre cada fila que requiere imputación
        for idx in indices_nulos:
            # Ordenar los niveles educativos candidatos según su porcentaje objetivo, de mayor a menor
            candidatos = dist_objetivo.sort_values(ascending=False).index.tolist()

            asignado = None

            # Intentar asignar cada candidato verificando que la desviación máxima no supere el 5%
            for educ in candidatos:
                # Simular la asignación de este nivel educativo incrementando el conteo actual
                conteo_sim = conteo_actual.copy()
                conteo_sim[educ] += 1
                total_sim = total_actual + 1

                # Calcular el porcentaje simulado tras la asignación
                porcentaje_sim = (conteo_sim / total_sim) * 100

                # Calcular la desviación absoluta entre el porcentaje simulado y el objetivo
                diferencia = (porcentaje_sim - dist_objetivo).abs()

                # Si la desviación máxima está dentro del rango aceptable, asignar este nivel educativo y salir del ciclo
                if diferencia.max() <= 5:
                    asignado = educ
                    break  # Asignación aceptable encontrada

            # Si ningún candidato cumple con la condición de desviación, asignar el segundo mejor candidato si existe
            if asignado is None:
                if len(candidatos) > 1:
                    asignado = candidatos[1]
                else:
                    # Si solo hay un candidato, asignarlo directamente
                    asignado = candidatos[0]

            # Asignar el nivel educativo elegido al dataframe copiado en el índice correspondiente
            df_copy.at[idx, 'fami_educacionpadre'] = asignado

            # Actualizar el conteo actual y el total para reflejar esta nueva asignación
            conteo_actual[asignado] += 1
            total_actual += 1

    # Retornar el dataframe con las imputaciones realizadas
    return df_copy

In [395]:
# Aplicar la función de imputación para la educación del padre en el dataframe df_final3,
# usando la distribución porcentual por estrato contenida en tabla_porcentajes_estrato_educacion_padre.
df_final4 = imputar_educacion_padre(df_final3, tabla_porcentajes_estrato_educacion_padre)
# Mostrar el dataframe resultante con los valores imputados
df_final4

,periodo,estu_tipodocumento,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,estu_genero,...,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global,combinacion
0,20172,TI,N,A,NaN,ANTIOQUIA,MIXTO,TARDE,OFICIAL,M,...,No,No,A-,43.0,51.0,40,54,49,240,"(No, No, No, No)"
1,20172,TI,N,A,ACADÉMICO,LA GUAJIRA,MIXTO,MAÑANA,OFICIAL,F,...,No,No,A-,35.0,38.0,35,36,35,180,"(No, No, No, No)"
2,20172,CC,N,A,TÉCNICO/ACADÉMICO,LA GUAJIRA,MIXTO,UNICA,OFICIAL,F,...,No,No,A-,37.0,47.0,45,52,53,242,"(No, No, No, No)"
3,20172,TI,S,A,TÉCNICO/ACADÉMICO,CAUCA,MIXTO,MAÑANA,OFICIAL,F,...,No,No,A-,44.0,47.0,40,43,51,226,"(No, No, No, No)"
4,20172,TI,N,A,ACADÉMICO,SUCRE,MIXTO,MAÑANA,OFICIAL,F,...,No,No,A-,35.0,38.0,47,46,42,213,"(No, No, No, No)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512389,20171,TI,S,B,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,M,...,Si,Si,B+,85.0,58.0,71,60,63,323,"(Si, Si, Si, Si)"
512390,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,M,...,Si,Si,A-,44.0,45.0,49,46,53,240,"(Si, Si, Si, Si)"
512391,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A2,65.0,50.0,50,46,54,256,"(Si, Si, Si, Si)"
512392,20172,TI,N,A,ACADÉMICO,BOGOTA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,55.0,49.0,51,52,55,260,"(Si, Si, Si, Si)"
512393,20172,TI,N,A,ACADÉMICO,ANTIOQUIA,MIXTO,COMPLETA,NO OFICIAL,F,...,Si,Si,A1,48.0,40.0,50,54,62,256,"(Si, Si, Si, Si)"

In [396]:
# Crear una tabla cruzada entre el estrato de vivienda y la educación del padre en df_final4
evaluacion4 = pd.crosstab(df_final4['fami_estratovivienda'], df_final4['fami_educacionpadre'])

# Calcular la suma total de cada fila (es decir, total de registros por estrato)
suma_por_fila = evaluacion4.sum(axis=1)

# Convertir los conteos absolutos a porcentajes dentro de cada estrato
# Dividiendo cada celda por la suma total de su fila y multiplicando por 100 para obtener %
evaluacion4 = evaluacion4.div(suma_por_fila, axis=0) * 100

# Mostrar la tabla con los porcentajes de distribución de la educación del padre por estrato
print(evaluacion4)

fami_educacionpadre   Educación profesional completa  \
fami_estratovivienda
Estrato 1                                   3.657903
Estrato 2                                   7.260832
Estrato 3                                  16.168352
Estrato 4                                  32.954007
Estrato 5                                  33.140390
Estrato 6                                  31.188590
Sin Estrato                                 4.273247

fami_educacionpadre   Educación profesional incompleta    Ninguno  Postgrado  \
fami_estratovivienda
Estrato 1                                     0.937371   5.866878   0.295735
Estrato 2                                     1.788152   2.906834   0.870147
Estrato 3                                     3.721427   2.138718   3.313492
Estrato 4                                     4.472894   3.283547  11.565513
Estrato 5                                     3.924262   4.414794  17.982929
Estrato 6                                     3.930269   4.896989  24.263074
Sin Estrato                                   1.594944  11.209750   0.744809

fami_educacionpadre   Primaria completa  Primaria incompleta  \
fami_estratovivienda
Estrato 1                     14.230300            36.185888
Estrato 2                     11.807893            19.179669
Estrato 3                      7.107485            10.202301
Estrato 4                      5.413308             6.665876
Estrato 5                      4.434416             6.376925
Estrato 6                      3.692552             6.133122
Sin Estrato                   13.414084            34.614806

fami_educacionpadre   Secundaria (Bachillerato) completa  \
fami_estratovivienda
Estrato 1                                      18.358347
Estrato 2                                      30.103819
Estrato 3                                      29.942046
Estrato 4                                      16.880038
Estrato 5                                      13.116845
Estrato 6                                      13.122029
Sin Estrato                                    15.377671

fami_educacionpadre   Secundaria (Bachillerato) incompleta  \
fami_estratovivienda
Estrato 1                                        14.982180
Estrato 2                                        16.348429
Estrato 3                                        14.083568
Estrato 4                                         8.661293
Estrato 5                                         8.231139
Estrato 6                                         6.339144
Sin Estrato                                      13.293711

fami_educacionpadre   Técnica o tecnológica completa  \
fami_estratovivienda
Estrato 1                                   4.171795
Estrato 2                                   7.491965
Estrato 3                                  10.265060
Estrato 4                                   7.712976
Estrato 5                                   5.297753
Estrato 6                                   3.961965
Sin Estrato                                 3.212459

fami_educacionpadre   Técnica o tecnológica incompleta
fami_estratovivienda
Estrato 1                                     1.313602
Estrato 2                                     2.242260
Estrato 3                                     3.057552
Estrato 4                                     2.390548
Estrato 5                                     3.080545
Estrato 6                                     2.472266
Sin Estrato                                   2.264520

In [397]:
# Contar la cantidad de datos faltantes en cada columna
numero_datos_faltantes = df_final4.isna().sum()
# Mostrar el resultado
print(numero_datos_faltantes)

periodo                         0
estu_tipodocumento              0
cole_bilingue                   0
cole_calendario                 0
cole_caracter                7573
cole_depto_ubicacion            0
cole_genero                     0
cole_jornada                    0
cole_naturaleza                 0
estu_genero                     0
estu_nacionalidad               0
estu_pais_reside                0
estu_privado_libertad           0
fami_cuartoshogar            8344
fami_educacionmadre             0
fami_educacionpadre             0
fami_estratovivienda            0
fami_personashogar          10901
fami_tieneautomovil             0
fami_tienecomputador            0
fami_tieneinternet              0
fami_tienelavadora              0
desemp_ingles                   0
punt_ingles                     0
punt_matematicas                0
punt_sociales_ciudadanas        0
punt_c_naturales                0
punt_lectura_critica            0
punt_global                     0
combinacion                     0
dtype: int64